global using Hyper.Domain.Entities.Analytics.Enums;
global using Hyper.Domain.Entities.CallCenter;
global using Hyper.Domain.Entities.Common;
global using Hyper.Domain.Entities.Customers;
global using Hyper.Domain.Entities.Customers.Enums;
global using Hyper.Domain.Entities.CustomerSegments.Enums;
global using Hyper.Domain.Entities.Events;
global using Hyper.Domain.Entities.Events.Data;
global using Hyper.Domain.Entities.Events.Enums;
global using Hyper.Domain.Entities.Feedback;
global using Hyper.Domain.Entities.Forum;
global using Hyper.Domain.Entities.Geography;
global using Hyper.Domain.Entities.Points;
global using Hyper.Domain.Entities.Points.Enums;
global using Hyper.Domain.Entities.Products;
global using Hyper.Domain.Entities.Products.Enums;
global using Hyper.Domain.Entities.Promotions;
global using Hyper.Domain.Entities.Promotions.Data;
global using Hyper.Domain.Entities.Promotions.Enums;
global using Hyper.Domain.Entities.Promotions.Plans;
global using Hyper.Domain.Entities.Promotions.Plans.Data;
global using Hyper.Domain.Entities.Promotions.Plans.Enums;
global using Hyper.Domain.Entities.Promotions.Surveys;
global using Hyper.Domain.Entities.Promotions.Surveys.Data;
global using Hyper.Domain.Entities.Promotions.Surveys.Enums;
global using Hyper.Domain.Entities.Rewards;
global using Hyper.Domain.Entities.Tenants;
global using Hyper.Domain.Entities.Tenants.Data;
global using Hyper.Domain.Entities.Tenants.Enums;
global using Hyper.Domain.Enums;
global using Hyper.Domain.Features.Attributes;
global using Hyper.Domain.Features.Client;
global using Hyper.Domain.Features.Customers;
global using Hyper.Domain.Features.Points;
global using Hyper.Domain.Features.Products;
global using Hyper.Domain.Features.Promotions;
global using Hyper.Domain.Features.Referal;
global using Hyper.Domain.Features.Rewards;
global using Hyper.Domain.Features.Themes;
global using Mapster;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Neo.Bpms.Domain.Models.Attributes.EntityAttributes;
global using Neo.Bpms.Domain.Models.Attributes.FieldAndEntityAttributes;
global using Neo.Bpms.Domain.Models.Attributes.FieldAttributes;
global using Neo.Common.Attributes;
global using Neo.Common.Extensions;
global using Neo.Domain.Entities.Base;
global using Neo.Domain.Entities.Common;
global using Neo.Domain.Features.Telementry;
global using Neo.Domain.Repository;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Data;
global using CustomerReferrer = Hyper.Domain.Entities.Referal.CustomerReferrer;
global using CustomerSegment = Hyper.Domain.Entities.CustomerSegments.CustomerSegment;
global using CustomerSegmentMembership = Hyper.Domain.Entities.CustomerSegments.Data.CustomerSegmentMembership;
global using EventChannel = Hyper.Domain.Entities.Channels.EventChannel;
global using EventLog = Hyper.Domain.Entities.Events.Data.EventLog;
global using PromotionEventReceived = Hyper.Domain.Entities.Promotions.Data.PromotionEventReceived;
global using PromotionParticipation = Hyper.Domain.Entities.Promotions.Data.PromotionParticipation;
global using PromotionRecipient = Hyper.Domain.Entities.Promotions.Data.PromotionRecipient;
global using ReferrerCode = Hyper.Domain.Entities.Referal.ReferrerCode;
global using Tenant = Hyper.Domain.Entities.Tenants.Tenant;
