namespace BasalamSandbox;

public static class Html
{
    private const string Style = "body{font-family:Tahoma,Arial;background:#f5f6f8;color:#253044;margin:0}.top{background:#ff5b35;color:white;padding:18px 8%;display:flex;justify-content:space-between}.wrap{max-width:980px;margin:35px auto;padding:0 18px}.card{background:white;border-radius:16px;padding:28px;box-shadow:0 8px 24px #17203314;margin-bottom:18px}.badge{color:#ff5b35;font-weight:bold}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}.vendor{border:1px solid #e4e8ef;border-radius:12px;padding:16px}.btn{background:#ff5b35;color:white;border:0;border-radius:9px;padding:12px 22px;font-size:15px;cursor:pointer}.muted{color:#687386;font-size:13px}table{width:100%;border-collapse:collapse}td,th{padding:12px;border-bottom:1px solid #edf0f4;text-align:right}input{padding:9px;border:1px solid #ccd3df;border-radius:7px;width:70px}a{color:#ff5b35}";
    public static string Consent(string client, string redirect, string scope, string state, IReadOnlyList<Vendor> vendors) => Page("تأیید دسترسی باسلام", $"<div class='card'><span class='badge'>SANDBOX / DEMO</span><h1>ورود و اعطای دسترسی</h1><p>این صفحه شبیه‌ساز باسلام برای تست یکپارچه‌سازی Hyper است و به باسلام واقعی متصل نیست.</p><p class='muted'>Client: {E(client)}<br>مجوز درخواستی: {E(scope)}</p><form method='post' action='/accounts/sso/consent'><input type='hidden' name='client_id' value='{E(client)}'><input type='hidden' name='redirect_uri' value='{E(redirect)}'><input type='hidden' name='scope' value='{E(scope)}'><input type='hidden' name='state' value='{E(state)}'><h3>غرفه دمو را انتخاب کنید</h3><div class='grid'>{string.Join("", vendors.Select(v => $"<label class='vendor'><input type='radio' name='vendor_id' value='{v.Id}' required><strong>{E(v.Title)}</strong><p class='muted'>{E(v.Identifier)}</p></label>"))}</div><br><button class='btn'>تأیید و بازگشت به Hyper</button></form></div>");
    public static string Vendor(IReadOnlyList<Vendor> vendors, IReadOnlyList<Product> products) => Page("محیط غرفه دمو", $"<div class='card'><span class='badge'>HYPER BASALAM SANDBOX</span><h1>محیط غرفه‌دار دمو</h1><p>داده‌ها در SQLite مستقل ذخیره می‌شوند و به دیتابیس Hyperyek دسترسی ندارند.</p><p class='muted'>برای اجرای OAuth، از دکمه ورود باسلام در پنل Hyper استفاده کنید؛ callback و ذخیره اتصال از همان مسیر واقعی انجام می‌شود.</p><form method='post' action='/sandbox/reset'><button class='btn'>بازنشانی داده‌ها</button></form></div><div class='card'><h2>غرفه‌ها</h2><div class='grid'>{string.Join("", vendors.Select(v => $"<div class='vendor'><strong>{E(v.Title)}</strong><p class='muted'>{E(v.Identifier)} · شناسه {v.Id}</p></div>"))}</div></div><div class='card'><h2>محصولات غرفه تجهیزات پزشکی</h2><table><tr><th>محصول</th><th>SKU</th><th>قیمت</th><th>موجودی</th><th>تغییر</th></tr>{string.Join("", products.Select(p => $"<tr><td>{E(p.Name)}</td><td>{E(p.Sku)}</td><td>{p.Price:N0}</td><td>{p.Stock}</td><td><form method='post' action='/sandbox/vendor/products/{p.Id}/stock'><input name='stock' type='number' min='0' value='{p.Stock}'><button class='btn'>ذخیره</button></form></td></tr>"))}</table></div>");
    public static string Error(string text) => Page("خطای Sandbox", $"<div class='card'><span class='badge'>SANDBOX</span><h1>درخواست نامعتبر</h1><p>{E(text)}</p></div>");
    private static string Page(string title, string body) => $"<!doctype html><html lang='fa' dir='rtl'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{E(title)}</title><style>{Style}</style></head><body><header class='top'><strong>باسلام دمو</strong><span>محیط توسعه Hyper</span></header><main class='wrap'>{body}</main></body></html>";
    private static string E(string value) => System.Net.WebUtility.HtmlEncode(value);
}
