using Microsoft.Data.SqlClient;
using System.Data;
using System.Security.Cryptography;

namespace BasalamSandbox;

/// <summary>Persistent sandbox database, intentionally separate from Hyperyek.</summary>
public sealed class SqlServerDemoStore(IConfiguration configuration)
{
    private readonly string _connectionString = BuildConnectionString(configuration);
    private readonly string _clientId = configuration["BasalamSandbox:ClientId"] ?? "hyper_yek";
    private readonly string _clientSecret = configuration["BasalamSandbox:ClientSecret"] ?? "demo-basalam-secret";
    private SqlConnection Open() { var c = new SqlConnection(_connectionString); c.Open(); return c; }

    public async Task InitializeAsync(CancellationToken ct)
    {
        await EnsureDatabaseAsync(ct);
        await using var db = Open(); await using var cmd = db.CreateCommand();
        cmd.CommandText = """
        IF OBJECT_ID(N'dbo.Vendors',N'U') IS NULL CREATE TABLE dbo.Vendors(Id bigint NOT NULL CONSTRAINT PK_Basalam_Vendors PRIMARY KEY,Identifier nvarchar(200) NOT NULL,Title nvarchar(300) NOT NULL,IsActive bit NOT NULL);
        IF OBJECT_ID(N'dbo.Products',N'U') IS NULL CREATE TABLE dbo.Products(Id bigint NOT NULL CONSTRAINT PK_Basalam_Products PRIMARY KEY,VendorId bigint NOT NULL,Sku nvarchar(200) NOT NULL,Name nvarchar(300) NOT NULL,Price bigint NOT NULL,Stock int NOT NULL,UpdatedAt datetime2(3) NOT NULL);
        IF OBJECT_ID(N'dbo.Variants',N'U') IS NULL CREATE TABLE dbo.Variants(Id bigint NOT NULL CONSTRAINT PK_Basalam_Variants PRIMARY KEY,ProductId bigint NOT NULL,Title nvarchar(300) NOT NULL,Sku nvarchar(200) NOT NULL,Price bigint NOT NULL,Stock int NOT NULL,UpdatedAt datetime2(3) NOT NULL);
        IF OBJECT_ID(N'dbo.AuthorizationCodes',N'U') IS NULL CREATE TABLE dbo.AuthorizationCodes(Code nvarchar(512) NOT NULL CONSTRAINT PK_Basalam_Codes PRIMARY KEY,ClientId nvarchar(200) NOT NULL,RedirectUri nvarchar(2048) NOT NULL,Scope nvarchar(2000) NULL,State nvarchar(max) NULL,VendorId bigint NOT NULL,Used bit NOT NULL CONSTRAINT DF_Basalam_CodeUsed DEFAULT 0,CreatedAt datetime2(3) NOT NULL);
        IF OBJECT_ID(N'dbo.Tokens',N'U') IS NULL CREATE TABLE dbo.Tokens(AccessToken nvarchar(512) NOT NULL CONSTRAINT PK_Basalam_Tokens PRIMARY KEY,RefreshToken nvarchar(512) NOT NULL,ClientId nvarchar(200) NOT NULL,VendorId bigint NOT NULL,ExpiresAt datetime2(3) NOT NULL);
        IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=N'IX_Basalam_Products_Vendor' AND object_id=OBJECT_ID(N'dbo.Products')) CREATE INDEX IX_Basalam_Products_Vendor ON dbo.Products(VendorId,Id);
        IF NOT EXISTS(SELECT 1 FROM dbo.Vendors WHERE Id=1001) INSERT dbo.Vendors VALUES(1001,N'demo-medical',N'غرفه نمونه تجهیزات پزشکی',1);
        IF NOT EXISTS(SELECT 1 FROM dbo.Vendors WHERE Id=1002) INSERT dbo.Vendors VALUES(1002,N'demo-home',N'غرفه نمونه خانه و زندگی',1);
        IF NOT EXISTS(SELECT 1 FROM dbo.Products WHERE Id=2001) INSERT dbo.Products VALUES(2001,1001,N'MED-001',N'فشارسنج دیجیتال دمو',1250000,12,SYSUTCDATETIME());
        IF NOT EXISTS(SELECT 1 FROM dbo.Products WHERE Id=2002) INSERT dbo.Products VALUES(2002,1001,N'MED-002',N'تب‌سنج لیزری دمو',450000,25,SYSUTCDATETIME());
        IF NOT EXISTS(SELECT 1 FROM dbo.Products WHERE Id=2003) INSERT dbo.Products VALUES(2003,1001,N'MED-003',N'پالس اکسیمتر دمو',780000,8,SYSUTCDATETIME());
        IF NOT EXISTS(SELECT 1 FROM dbo.Products WHERE Id=2101) INSERT dbo.Products VALUES(2101,1002,N'HOME-001',N'چراغ مطالعه دمو',320000,17,SYSUTCDATETIME());
        IF NOT EXISTS(SELECT 1 FROM dbo.Variants WHERE Id=31001) INSERT dbo.Variants VALUES(31001,2001,N'بازویی - سایز متوسط',N'MED-001-M',1290000,5,SYSUTCDATETIME());
        IF NOT EXISTS(SELECT 1 FROM dbo.Variants WHERE Id=31002) INSERT dbo.Variants VALUES(31002,2001,N'بازویی - سایز بزرگ',N'MED-001-L',1390000,7,SYSUTCDATETIME());
        """; await cmd.ExecuteNonQueryAsync(ct);
    }
    public bool IsClient(string clientId) => clientId == _clientId;
    public async Task<IReadOnlyList<Vendor>> ListVendorsAsync(CancellationToken ct) { await using var db=Open(); await using var c=Cmd(db,"SELECT Id,Identifier,Title FROM dbo.Vendors WHERE IsActive=1 ORDER BY Id"); var r=new List<Vendor>(); await using var x=await c.ExecuteReaderAsync(ct); while(await x.ReadAsync(ct)) r.Add(new(x.GetInt64(0),x.GetString(1),x.GetString(2))); return r; }
    public async Task<IReadOnlyList<Product>> ListProductsAsync(long vendorId,CancellationToken ct) { await using var db=Open(); await using var c=Cmd(db,"SELECT p.Id,p.Sku,p.Name,p.Price,COALESCE((SELECT SUM(v.Stock) FROM dbo.Variants v WHERE v.ProductId=p.Id),p.Stock) FROM dbo.Products p WHERE p.VendorId=@v ORDER BY p.Id"); Add(c,"@v",vendorId); var r=new List<Product>(); await using var x=await c.ExecuteReaderAsync(ct); while(await x.ReadAsync(ct)) r.Add(new(x.GetInt64(0),x.GetString(1),x.GetString(2),x.GetInt64(3),x.GetInt32(4))); return r; }
    public async Task<ProductDetails?> GetProductAsync(long id,CancellationToken ct) { await using var db=Open(); await using var c=Cmd(db,"SELECT Id,VendorId,Sku,Name,Price,COALESCE((SELECT SUM(v.Stock) FROM dbo.Variants v WHERE v.ProductId=Products.Id),Stock) FROM dbo.Products WHERE Id=@id"); Add(c,"@id",id); await using var x=await c.ExecuteReaderAsync(ct); return await x.ReadAsync(ct)?new(x.GetInt64(0),x.GetInt64(1),x.GetString(2),x.GetString(3),x.GetInt64(4),x.GetInt32(5)):null; }
    public async Task<bool> VendorExistsAsync(long id,CancellationToken ct) { await using var db=Open(); await using var c=Cmd(db,"SELECT COUNT_BIG(1) FROM dbo.Vendors WHERE Id=@id AND IsActive=1"); Add(c,"@id",id); return Convert.ToInt64(await c.ExecuteScalarAsync(ct))==1; }
    public async Task<string> CreateAuthorizationCodeAsync(string clientId,string redirect,string scope,string state,long vendorId,CancellationToken ct) { var code="demo_code_"+Convert.ToHexString(RandomNumberGenerator.GetBytes(18)).ToLowerInvariant(); await using var db=Open(); await using var c=Cmd(db,"INSERT dbo.AuthorizationCodes(Code,ClientId,RedirectUri,Scope,State,VendorId,CreatedAt) VALUES(@code,@client,@redirect,@scope,@state,@vendor,SYSUTCDATETIME())"); Add(c,"@code",code);Add(c,"@client",clientId);Add(c,"@redirect",redirect);Add(c,"@scope",scope);Add(c,"@state",state);Add(c,"@vendor",vendorId);await c.ExecuteNonQueryAsync(ct);return code; }
    public async Task<object?> ExchangeCodeAsync(string code,string clientId,string secret,string redirect,CancellationToken ct) { if(clientId!=_clientId||secret!=_clientSecret)return null; await using var db=Open(); await using var tx=(SqlTransaction)await db.BeginTransactionAsync(IsolationLevel.Serializable,ct); await using var c=Cmd(db,"SELECT VendorId FROM dbo.AuthorizationCodes WITH(UPDLOCK,HOLDLOCK) WHERE Code=@code AND ClientId=@client AND RedirectUri=@redirect AND Used=0 AND CreatedAt>=DATEADD(MINUTE,-10,SYSUTCDATETIME())",tx);Add(c,"@code",code);Add(c,"@client",clientId);Add(c,"@redirect",redirect);await using var x=await c.ExecuteReaderAsync(ct);if(!await x.ReadAsync(ct))return null;var vendor=x.GetInt64(0);await x.DisposeAsync();var access="demo_access_"+Convert.ToHexString(RandomNumberGenerator.GetBytes(24)).ToLowerInvariant();var refresh="demo_refresh_"+Convert.ToHexString(RandomNumberGenerator.GetBytes(24)).ToLowerInvariant();await using var u=Cmd(db,"UPDATE dbo.AuthorizationCodes SET Used=1 WHERE Code=@code",tx);Add(u,"@code",code);await u.ExecuteNonQueryAsync(ct);await using var i=Cmd(db,"INSERT dbo.Tokens VALUES(@access,@refresh,@client,@vendor,DATEADD(HOUR,1,SYSUTCDATETIME()))",tx);Add(i,"@access",access);Add(i,"@refresh",refresh);Add(i,"@client",clientId);Add(i,"@vendor",vendor);await i.ExecuteNonQueryAsync(ct);await tx.CommitAsync(ct);return new{token_type="Bearer",expires_in=3600,access_token=access,refresh_token=refresh,scope="vendor.profile.read"}; }
    public async Task<object?> RefreshAsync(string refresh,string clientId,string secret,CancellationToken ct) { if(clientId!=_clientId||secret!=_clientSecret)return null;await using var db=Open();await using var c=Cmd(db,"SELECT VendorId FROM dbo.Tokens WHERE RefreshToken=@refresh AND ClientId=@client");Add(c,"@refresh",refresh);Add(c,"@client",clientId);var vendor=await c.ExecuteScalarAsync(ct);if(vendor is null)return null;var access="demo_access_"+Convert.ToHexString(RandomNumberGenerator.GetBytes(24)).ToLowerInvariant();await using var i=Cmd(db,"INSERT dbo.Tokens VALUES(@access,@refresh,@client,@vendor,DATEADD(HOUR,1,SYSUTCDATETIME()))");Add(i,"@access",access);Add(i,"@refresh",refresh);Add(i,"@client",clientId);Add(i,"@vendor",vendor);await i.ExecuteNonQueryAsync(ct);return new{token_type="Bearer",expires_in=3600,access_token=access,refresh_token=refresh,scope="vendor.profile.read"}; }
    public async Task<bool> TokenValidAsync(HttpRequest request,CancellationToken ct)=>await TokenVendorAsync(request,null,ct) is not null;
    public async Task<bool> TokenAllowsVendorAsync(HttpRequest request,long id,CancellationToken ct)=>await TokenVendorAsync(request,id,ct) is not null;
    private async Task<long?> TokenVendorAsync(HttpRequest request,long? expected,CancellationToken ct){var raw=request.Headers.Authorization.ToString();if(!raw.StartsWith("Bearer ",StringComparison.OrdinalIgnoreCase))return null;await using var db=Open();await using var c=Cmd(db,"SELECT VendorId FROM dbo.Tokens WHERE AccessToken=@token AND ExpiresAt>SYSUTCDATETIME()");Add(c,"@token",raw[7..].Trim());var v=await c.ExecuteScalarAsync(ct);if(v is null)return null;var id=Convert.ToInt64(v);return expected is null||expected==id?id:null;}
    public async Task<VendorProfile?> VendorForTokenAsync(HttpRequest request,CancellationToken ct){var id=await TokenVendorAsync(request,null,ct);if(id is null)return null;await using var db=Open();await using var c=Cmd(db,"SELECT Id,Identifier,Title FROM dbo.Vendors WHERE Id=@id");Add(c,"@id",id);await using var x=await c.ExecuteReaderAsync(ct);return await x.ReadAsync(ct)?new(x.GetInt64(0),x.GetString(1),x.GetString(2)):null;}
    public async Task<bool> ChangeStockAsync(long id,int stock,CancellationToken ct){await using var db=Open();await using var c=Cmd(db,"UPDATE dbo.Products SET Stock=@stock,UpdatedAt=SYSUTCDATETIME() WHERE Id=@id");Add(c,"@stock",stock);Add(c,"@id",id);return await c.ExecuteNonQueryAsync(ct)==1;}
    public async Task<bool> ChangeVariantStockAsync(long id,int stock,CancellationToken ct){await using var db=Open();await using var c=Cmd(db,"UPDATE dbo.Variants SET Stock=@stock,UpdatedAt=SYSUTCDATETIME() WHERE Id=@id");Add(c,"@stock",stock);Add(c,"@id",id);return await c.ExecuteNonQueryAsync(ct)==1;}
    public async Task<IReadOnlyList<Variant>> ListVariantsAsync(long id,CancellationToken ct){await using var db=Open();await using var c=Cmd(db,"SELECT Id,ProductId,Title,Sku,Price,Stock FROM dbo.Variants WHERE ProductId=@id ORDER BY Id");Add(c,"@id",id);var r=new List<Variant>();await using var x=await c.ExecuteReaderAsync(ct);while(await x.ReadAsync(ct))r.Add(new(x.GetInt64(0),x.GetInt64(1),x.GetString(2),x.GetString(3),x.GetInt64(4),x.GetInt32(5)));return r;}
    public async Task ResetAsync(CancellationToken ct){await using var db=Open();await using var c=Cmd(db,"UPDATE dbo.Products SET Stock=CASE Id WHEN 2001 THEN 12 WHEN 2002 THEN 25 WHEN 2003 THEN 8 WHEN 2101 THEN 17 ELSE Stock END,UpdatedAt=SYSUTCDATETIME();UPDATE dbo.Variants SET Stock=CASE Id WHEN 31001 THEN 5 WHEN 31002 THEN 7 ELSE Stock END,UpdatedAt=SYSUTCDATETIME()");await c.ExecuteNonQueryAsync(ct);}
    private static SqlCommand Cmd(SqlConnection db,string text,SqlTransaction? tx=null){var c=db.CreateCommand();c.CommandText=text;c.Transaction=tx;return c;} private static void Add(SqlCommand c,string n,object? v)=>c.Parameters.AddWithValue(n,v??DBNull.Value);
    private async Task EnsureDatabaseAsync(CancellationToken ct){var target=new SqlConnectionStringBuilder(_connectionString);var name=target.InitialCatalog;if(string.IsNullOrWhiteSpace(name)||name.Equals("master",StringComparison.OrdinalIgnoreCase))return;target.InitialCatalog="master";await using var db=new SqlConnection(target.ConnectionString);await db.OpenAsync(ct);await using var c=db.CreateCommand();c.CommandText="IF DB_ID(@name) IS NULL BEGIN DECLARE @sql nvarchar(512)=N'CREATE DATABASE '+QUOTENAME(@name); EXEC(@sql); END";Add(c,"@name",name);await c.ExecuteNonQueryAsync(ct);}
    private static string BuildConnectionString(IConfiguration configuration){var value=configuration.GetConnectionString("BasalamSandbox")??configuration["BasalamSandbox:ConnectionString"];if(string.IsNullOrWhiteSpace(value))throw new InvalidOperationException("ConnectionStrings:BasalamSandbox is required.");var b=new SqlConnectionStringBuilder(value){TrustServerCertificate=true,Encrypt=false};if(string.IsNullOrWhiteSpace(b.InitialCatalog))b.InitialCatalog="BasalamSandbox";return b.ConnectionString;}
}
