using Hyper.AdminPanel.Domain.UiDefinitions.HomePage;
using Hyper.Domain.Entities.Database;
namespace Hyper.AdminPanel.Domain.Domain;
public partial class HyperMenuDefinitions : MenuDefinition
{
    private void AddMenu_Hyper()
    {
        AddMenu<HomePageEntity, HomePageEntityUiDefinitions.HomePageDashboard>("داشبورد هایپریک", "home-dashboard");
        AddMenu("مغازه‌دار و اتصال", "building-organization", "MerchantSimulation", "Index");
        AddMenu("عملیات یکسان‌سازی", "activity-monitor", "MerchantSimulation", "Dashboard");
        AddMenu("یکسان‌سازی پروفایل", "user-circle", "MerchantSimulation", "Profile");
        AddMenu("مدیریت کار", "task-list", "WorkManagementPage", "Index");
        AddMenu("اطلاعات پایه مغازه", "database", "HyperCategory0", "");
        {
            StartSubMenus();
            AddMenu<SqlTblGeneralconfig>("تنظیمات کلی فروشگاه", "table");
            AddMenu<SqlTblPerson>("شخص", "table");
            AddMenu<SqlTblPrintconfig>("تنظیمات چاپ", "table");
            AddMenu<SqlTblProject>("پروژه", "table");
            AddMenu<SqlTblShareholder>("سهامدار", "table");
            AddMenu<SqlTblShop>("مغازه", "table");
            AddMenu<SqlTblShopactivitytype>("نوع فعالیت فروشگاه", "table");
            AddMenu<SqlTblTaxpayerportalconfig>("تنظیمات سامانه مودیان", "table");
            AddMenu<SqlTblWarehouse>("انبار", "table");
            AddMenu("گزارش‌ها", "chart-bar", "HyperReports0", "");
            {
                StartSubMenus();
                AddReport<SqlTblGeneralconfig>("گزارش تنظیمات کلی فروشگاه", "chart-bar");
                AddReport<SqlTblPerson>("گزارش شخص", "chart-bar");
                AddReport<SqlTblPrintconfig>("گزارش تنظیمات چاپ", "chart-bar");
                AddReport<SqlTblProject>("گزارش پروژه", "chart-bar");
                AddReport<SqlTblShareholder>("گزارش سهامدار", "chart-bar");
                AddReport<SqlTblShop>("گزارش مغازه", "chart-bar");
                AddReport<SqlTblShopactivitytype>("گزارش نوع فعالیت فروشگاه", "chart-bar");
                AddReport<SqlTblTaxpayerportalconfig>("گزارش تنظیمات سامانه مودیان", "chart-bar");
                AddReport<SqlTblWarehouse>("گزارش انبار", "chart-bar");
                EndSubMenus();
            }
            EndSubMenus();
        }
        AddMenu("کالا و موجودی", "database", "HyperCategory1", "");
        {
            StartSubMenus();
            AddMenu<SqlTblGlobalproduct>("محصول هایپریک", "table");
            AddMenu<SqlTblGlobalproductgroup>("گروه محصول هایپریک", "table");
            AddMenu<SqlTblGlobalproductmedia>("رسانه محصول", "table");
            AddMenu<SqlTblInventoryfifoconsumption>("مصرف لایه‌های FIFO", "table");
            AddMenu<SqlTblInventoryfifolayer>("لایه موجودی FIFO", "table");
            AddMenu<SqlTblProduct>("محصول", "table");
            AddMenu<SqlTblProductbarcode>("بارکد محصول", "table");
            AddMenu<SqlTblProductbrand>("برند محصول", "table");
            AddMenu<SqlTblProductreviewstatus>("وضعیت فراوری محصول", "table");
            AddMenu<SqlTblProductunit>("واحد اندازه‌گیری محصول", "table");
            AddMenu<SqlTblStockcard>("کاردکس انبار", "table");
            AddMenu<SqlTblStockcarditem>("آیتم کاردکس انبار", "table");
            AddMenu<SqlTblStocktaking>("انبارگردانی", "table");
            AddMenu<SqlTblStocktakingitem>("آیتم انبارگردانی", "table");
            AddMenu("گزارش‌ها", "chart-bar", "HyperReports1", "");
            {
                StartSubMenus();
                AddReport<SqlTblGlobalproduct>("گزارش محصول هایپریک", "chart-bar");
                AddReport<SqlTblGlobalproductgroup>("گزارش گروه محصول هایپریک", "chart-bar");
                AddReport<SqlTblGlobalproductmedia>("گزارش رسانه محصول", "chart-bar");
                AddReport<SqlTblInventoryfifoconsumption>("گزارش مصرف لایه‌های FIFO", "chart-bar");
                AddReport<SqlTblInventoryfifolayer>("گزارش لایه موجودی FIFO", "chart-bar");
                AddReport<SqlTblProduct>("گزارش محصول", "chart-bar");
                AddReport<SqlTblProductbarcode>("گزارش بارکد محصول", "chart-bar");
                AddReport<SqlTblProductbrand>("گزارش برند محصول", "chart-bar");
                AddReport<SqlTblProductreviewstatus>("گزارش وضعیت فراوری محصول", "chart-bar");
                AddReport<SqlTblProductunit>("گزارش واحد اندازه‌گیری محصول", "chart-bar");
                AddReport<SqlTblStockcard>("گزارش کاردکس انبار", "chart-bar");
                AddReport<SqlTblStockcarditem>("گزارش آیتم کاردکس انبار", "chart-bar");
                AddReport<SqlTblStocktaking>("گزارش انبارگردانی", "chart-bar");
                AddReport<SqlTblStocktakingitem>("گزارش آیتم انبارگردانی", "chart-bar");
                EndSubMenus();
            }
            EndSubMenus();
        }
        AddMenu("حسابداری و اسناد", "database", "HyperCategory2", "");
        {
            StartSubMenus();
            AddMenu<SqlTblAccount>("حساب", "table");
            AddMenu<SqlTblAccountingarticle>("آرتیکل حسابداری", "table");
            AddMenu<SqlTblAccountingdocument>("سند حسابداری", "table");
            AddMenu<SqlTblBankaccount>("حساب بانکی", "table");
            AddMenu<SqlTblCashfund>("صندوق نقدی", "table");
            AddMenu<SqlTblCheck>("چک", "table");
            AddMenu<SqlTblDetailaccount>("حساب تفصیلی", "table");
            AddMenu<SqlTblPettycash>("تنخواه", "table");
            AddMenu<SqlTblPosdevice>("دستگاه کارتخوان", "table");
            AddMenu<SqlTblShopfiscalperiod>("دوره مالی فروشگاه", "table");
            AddMenu<SqlTblTransfer>("انتقال", "table");
            AddMenu<SqlTblTransferitem>("آیتم انتقال", "table");
            AddMenu("گزارش‌ها", "chart-bar", "HyperReports2", "");
            {
                StartSubMenus();
                AddReport<SqlTblAccount>("گزارش حساب", "chart-bar");
                AddReport<SqlTblAccountingarticle>("گزارش آرتیکل حسابداری", "chart-bar");
                AddReport<SqlTblAccountingdocument>("گزارش سند حسابداری", "chart-bar");
                AddReport<SqlTblBankaccount>("گزارش حساب بانکی", "chart-bar");
                AddReport<SqlTblCashfund>("گزارش صندوق نقدی", "chart-bar");
                AddReport<SqlTblCheck>("گزارش چک", "chart-bar");
                AddReport<SqlTblDetailaccount>("گزارش حساب تفصیلی", "chart-bar");
                AddReport<SqlTblPettycash>("گزارش تنخواه", "chart-bar");
                AddReport<SqlTblPosdevice>("گزارش دستگاه کارتخوان", "chart-bar");
                AddReport<SqlTblShopfiscalperiod>("گزارش دوره مالی فروشگاه", "chart-bar");
                AddReport<SqlTblTransfer>("گزارش انتقال", "chart-bar");
                AddReport<SqlTblTransferitem>("گزارش آیتم انتقال", "chart-bar");
                EndSubMenus();
            }
            EndSubMenus();
        }
        AddMenu("خرید و فروش", "database", "HyperCategory3", "");
        {
            StartSubMenus();
            AddMenu<SqlTblPurchaseorder>("فاکتور خرید", "table");
            AddMenu<SqlTblPurchaseorderitem>("اقلام فاکتور خرید", "table");
            AddMenu<SqlTblPurchaseorderreturn>("فاکتور برگشت از خرید", "table");
            AddMenu<SqlTblPurchaseorderreturnitem>("اقلام فاکتور برگشت از خرید", "table");
            AddMenu<SqlTblSaleorder>("فاکتور فروش", "table");
            AddMenu<SqlTblSaleorderconfig>("تنظیمات فروش", "table");
            AddMenu<SqlTblSaleorderitem>("اقلام فاکتور فروش", "table");
            AddMenu<SqlTblSaleorderreturn>("فاکتور برگشت از فروش", "table");
            AddMenu<SqlTblSaleorderreturnitem>("اقلام فاکتور برگشت از فروش", "table");
            AddMenu("گزارش‌ها", "chart-bar", "HyperReports3", "");
            {
                StartSubMenus();
                AddReport<SqlTblPurchaseorder>("گزارش فاکتور خرید", "chart-bar");
                AddReport<SqlTblPurchaseorderitem>("گزارش اقلام فاکتور خرید", "chart-bar");
                AddReport<SqlTblPurchaseorderreturn>("گزارش فاکتور برگشت از خرید", "chart-bar");
                AddReport<SqlTblPurchaseorderreturnitem>("گزارش اقلام فاکتور برگشت از خرید", "chart-bar");
                AddReport<SqlTblSaleorder>("گزارش فاکتور فروش", "chart-bar");
                AddReport<SqlTblSaleorderconfig>("گزارش تنظیمات فروش", "chart-bar");
                AddReport<SqlTblSaleorderitem>("گزارش اقلام فاکتور فروش", "chart-bar");
                AddReport<SqlTblSaleorderreturn>("گزارش فاکتور برگشت از فروش", "chart-bar");
                AddReport<SqlTblSaleorderreturnitem>("گزارش اقلام فاکتور برگشت از فروش", "chart-bar");
                EndSubMenus();
            }
            EndSubMenus();
        }
        AddMenu("اتصال و یکسان‌سازی", "database", "HyperCategory4", "");
        {
            StartSubMenus();
            AddMenu<SqlExternalintegrationconnections>("خارجی یکسان‌سازی اتصال‌ها", "table");
            AddMenu<SqlExternalordermappings>("خارجی سفارش نگاشت‌ها", "table");
            AddMenu<SqlExternalproductmappings>("خارجی کالا نگاشت‌ها", "table");
            AddMenu<SqlIntegrationadminsimulations>("یکسان‌سازی ادمین شبیه‌سازی‌ها", "table");
            AddMenu<SqlIntegrationeventaudits>("یکسان‌سازی رویداد ممیزی‌ها", "table");
            AddMenu<SqlIntegrationmerchantaccess>("یکسان‌سازی مغازه‌دار دسترسی", "table");
            AddMenu<SqlIntegrationoutbox>("یکسان‌سازی صف خروجی", "table");
            AddMenu<SqlIntegrationsyncruns>("یکسان‌سازی یکسان‌سازی اجراها", "table");
            AddMenu<SqlIntegrationtokenrequests>("یکسان‌سازی توکن درخواست‌ها", "table");
            AddMenu<SqlIntegrationwebhookinbox>("یکسان‌سازی وب‌هوک صندوق ورودی", "table");
            AddMenu<SqlInventoryreservationlogs>("موجودی رزرو سوابق", "table");
            AddMenu("گزارش‌ها", "chart-bar", "HyperReports4", "");
            {
                StartSubMenus();
                AddReport<SqlExternalintegrationconnections>("گزارش خارجی یکسان‌سازی اتصال‌ها", "chart-bar");
                AddReport<SqlExternalordermappings>("گزارش خارجی سفارش نگاشت‌ها", "chart-bar");
                AddReport<SqlExternalproductmappings>("گزارش خارجی کالا نگاشت‌ها", "chart-bar");
                AddReport<SqlIntegrationadminsimulations>("گزارش یکسان‌سازی ادمین شبیه‌سازی‌ها", "chart-bar");
                AddReport<SqlIntegrationeventaudits>("گزارش یکسان‌سازی رویداد ممیزی‌ها", "chart-bar");
                AddReport<SqlIntegrationmerchantaccess>("گزارش یکسان‌سازی مغازه‌دار دسترسی", "chart-bar");
                AddReport<SqlIntegrationoutbox>("گزارش یکسان‌سازی صف خروجی", "chart-bar");
                AddReport<SqlIntegrationsyncruns>("گزارش یکسان‌سازی یکسان‌سازی اجراها", "chart-bar");
                AddReport<SqlIntegrationtokenrequests>("گزارش یکسان‌سازی توکن درخواست‌ها", "chart-bar");
                AddReport<SqlIntegrationwebhookinbox>("گزارش یکسان‌سازی وب‌هوک صندوق ورودی", "chart-bar");
                AddReport<SqlInventoryreservationlogs>("گزارش موجودی رزرو سوابق", "chart-bar");
                EndSubMenus();
            }
            EndSubMenus();
        }
        AddMenu("خدمات و تنظیمات", "database", "HyperCategory5", "");
        {
            StartSubMenus();
            AddMenu<SqlTblAutoprocesslog>("لاگ فرایند خودکار", "table");
            AddMenu<SqlTblCredittransaction>("تراکنش‌های کیف پول", "table");
            AddMenu<SqlTblEntityfile>("فایل‌ها", "table");
            AddMenu<SqlTblEntitynote>("یادداشت موجودیت", "table");
            AddMenu<SqlTblGlobalconfig>("عمومی تنظیمات", "table");
            AddMenu<SqlTblGroups>("گروه‌ها", "table");
            AddMenu<SqlTblIrancities>("شهرهای ایران", "table");
            AddMenu<SqlTblIranstates>("استان‌های ایران", "table");
            AddMenu<SqlTblMessagehistory>("تاریخچه پیامک‌ها", "table");
            AddMenu<SqlTblNotificationconfig>("تنظیمات اعلانات", "table");
            AddMenu<SqlTblReleasenote>("تغییرات نسخه", "table");
            AddMenu<SqlTblReleasenoteitem>("آیتم تغییرات نسخه", "table");
            AddMenu<SqlTblServicediscount>("تخفیف اشتراک", "table");
            AddMenu<SqlTblServicepayment>("پرداخت سرویس", "table");
            AddMenu<SqlTblServiceplan>("نوع دسترسی اشتراک", "table");
            AddMenu<SqlTblServicerequest>("درخواست اشتراک", "table");
            AddMenu<SqlTblServicesubscription>("نوع اشتراک", "table");
            AddMenu<SqlTblShopnotification>("اعلان فروشگاه", "table");
            AddMenu<SqlTblShopnotificationinmemberrole>("اعلان فروشگاه در نقش عضو فروشگاه", "table");
            AddMenu<SqlTblShopnotificationinshop>("اعلان فروشگاه در فروشگاه", "table");
            AddMenu<SqlTblShopnotificationtype>("نوع اعلان فروشگاه", "table");
            AddMenu<SqlTblTag>("برچسب", "table");
            AddMenu<SqlTblUploadfile>("بارگذاری فایل‌ها", "table");
            AddMenu<SqlTblUseractionlog>("تاریخچه عملیات کاربران", "table");
            AddMenu<SqlViewAccountbalance>("حساب مانده", "table");
            AddMenu<SqlViewDetailaccountbalance>("تفصیلی حساب مانده", "table");
            AddMenu<SqlVwIntegrationdashboard>("یکسان‌سازی داشبورد", "table");
            AddMenu("گزارش‌ها", "chart-bar", "HyperReports5", "");
            {
                StartSubMenus();
                AddReport<SqlTblAutoprocesslog>("گزارش لاگ فرایند خودکار", "chart-bar");
                AddReport<SqlTblCredittransaction>("گزارش تراکنش‌های کیف پول", "chart-bar");
                AddReport<SqlTblEntityfile>("گزارش فایل‌ها", "chart-bar");
                AddReport<SqlTblEntitynote>("گزارش یادداشت موجودیت", "chart-bar");
                AddReport<SqlTblGlobalconfig>("گزارش عمومی تنظیمات", "chart-bar");
                AddReport<SqlTblGroups>("گزارش گروه‌ها", "chart-bar");
                AddReport<SqlTblIrancities>("گزارش شهرهای ایران", "chart-bar");
                AddReport<SqlTblIranstates>("گزارش استان‌های ایران", "chart-bar");
                AddReport<SqlTblMessagehistory>("گزارش تاریخچه پیامک‌ها", "chart-bar");
                AddReport<SqlTblNotificationconfig>("گزارش تنظیمات اعلانات", "chart-bar");
                AddReport<SqlTblReleasenote>("گزارش تغییرات نسخه", "chart-bar");
                AddReport<SqlTblReleasenoteitem>("گزارش آیتم تغییرات نسخه", "chart-bar");
                AddReport<SqlTblServicediscount>("گزارش تخفیف اشتراک", "chart-bar");
                AddReport<SqlTblServicepayment>("گزارش پرداخت سرویس", "chart-bar");
                AddReport<SqlTblServiceplan>("گزارش نوع دسترسی اشتراک", "chart-bar");
                AddReport<SqlTblServicerequest>("گزارش درخواست اشتراک", "chart-bar");
                AddReport<SqlTblServicesubscription>("گزارش نوع اشتراک", "chart-bar");
                AddReport<SqlTblShopnotification>("گزارش اعلان فروشگاه", "chart-bar");
                AddReport<SqlTblShopnotificationinmemberrole>("گزارش اعلان فروشگاه در نقش عضو فروشگاه", "chart-bar");
                AddReport<SqlTblShopnotificationinshop>("گزارش اعلان فروشگاه در فروشگاه", "chart-bar");
                AddReport<SqlTblShopnotificationtype>("گزارش نوع اعلان فروشگاه", "chart-bar");
                AddReport<SqlTblTag>("گزارش برچسب", "chart-bar");
                AddReport<SqlTblUploadfile>("گزارش بارگذاری فایل‌ها", "chart-bar");
                AddReport<SqlTblUseractionlog>("گزارش تاریخچه عملیات کاربران", "chart-bar");
                AddReport<SqlViewAccountbalance>("گزارش حساب مانده", "chart-bar");
                AddReport<SqlViewDetailaccountbalance>("گزارش تفصیلی حساب مانده", "chart-bar");
                AddReport<SqlVwIntegrationdashboard>("گزارش یکسان‌سازی داشبورد", "chart-bar");
                EndSubMenus();
            }
            EndSubMenus();
        }
        AddMenu("موجودیت های موتور", "database", "HyperCategory6", "");
        {
            StartSubMenus();
            AddMenu<SqlActGeBytearray>("موتور: داده باینری", "table");
            AddMenu<SqlActGeProperty>("موتور: ویژگی", "table");
            AddMenu<SqlActGeSchemaLog>("موتور: سوابق", "table");
            AddMenu<SqlActHiActinst>("سوابق موتور: نمونه فعالیت", "table");
            AddMenu<SqlActHiAttachment>("سوابق موتور: پیوست", "table");
            AddMenu<SqlActHiBatch>("سوابق موتور: دسته", "table");
            AddMenu<SqlActHiCaseactinst>("سوابق موتور: نمونه فعالیت پرونده", "table");
            AddMenu<SqlActHiCaseinst>("سوابق موتور: نمونه پرونده", "table");
            AddMenu<SqlActHiComment>("سوابق موتور: نظر", "table");
            AddMenu<SqlActHiDecIn>("سوابق موتور: ورودی", "table");
            AddMenu<SqlActHiDecOut>("سوابق موتور: خروجی", "table");
            AddMenu<SqlActHiDecinst>("سوابق موتور: نمونه تصمیم", "table");
            AddMenu<SqlActHiDetail>("سوابق موتور: تفصیلی", "table");
            AddMenu<SqlActHiExtTaskLog>("سوابق موتور: سوابق", "table");
            AddMenu<SqlActHiIdentitylink>("سوابق موتور: پیوند هویت", "table");
            AddMenu<SqlActHiIncident>("سوابق موتور: رخداد خطا", "table");
            AddMenu<SqlActHiJobLog>("سوابق موتور: سوابق", "table");
            AddMenu<SqlActHiOpLog>("سوابق موتور: سوابق", "table");
            AddMenu<SqlActHiProcinst>("سوابق موتور: نمونه فرایند", "table");
            AddMenu<SqlActHiTaskinst>("سوابق موتور: نمونه وظیفه", "table");
            AddMenu<SqlActHiVarinst>("سوابق موتور: نمونه متغیر", "table");
            AddMenu<SqlActIdGroup>("موتور: گروه", "table");
            AddMenu<SqlActIdInfo>("موتور: اطلاعات", "table");
            AddMenu<SqlActIdMembership>("موتور: عضویت", "table");
            AddMenu<SqlActIdRememberMe>("موتور: من", "table");
            AddMenu<SqlActIdTenant>("موتور: مستاجر", "table");
            AddMenu<SqlActIdTenantMember>("موتور: عضو", "table");
            AddMenu<SqlActIdUser>("موتور: کاربر", "table");
            AddMenu<SqlActReAssociation>("موتور: ارتباط", "table");
            AddMenu<SqlActReCamformdef>("موتور: تعریف فرم موتور", "table");
            AddMenu<SqlActReCaseDef>("موتور: تعریف", "table");
            AddMenu<SqlActReColumn>("موتور: ستون", "table");
            AddMenu<SqlActReConstraint>("موتور: محدودیت", "table");
            AddMenu<SqlActReDashboard>("موتور: داشبورد", "table");
            AddMenu<SqlActReDataForm>("موتور: فرم", "table");
            AddMenu<SqlActReDataFormColumn>("موتور: ستون", "table");
            AddMenu<SqlActReDataFormFilter>("موتور: فیلتر", "table");
            AddMenu<SqlActReDataFormHeader>("موتور: سرصفحه", "table");
            AddMenu<SqlActReDataFormSort>("موتور: مرتب‌سازی", "table");
            AddMenu<SqlActReDataReport>("موتور: گزارش", "table");
            AddMenu<SqlActReDataReportColumn>("موتور: ستون", "table");
            AddMenu<SqlActReDataReportFilter>("موتور: فیلتر", "table");
            AddMenu<SqlActReDataReportHeader>("موتور: سرصفحه", "table");
            AddMenu<SqlActReDataReportSort>("موتور: مرتب‌سازی", "table");
            AddMenu<SqlActReDecisionDef>("موتور: تعریف", "table");
            AddMenu<SqlActReDecisionReqDef>("موتور: تعریف", "table");
            AddMenu<SqlActReDeployment>("موتور: استقرار", "table");
            AddMenu<SqlActReForm>("موتور: فرم", "table");
            AddMenu<SqlActReLink>("موتور: پیوند", "table");
            AddMenu<SqlActReMenu>("موتور: منو", "table");
            AddMenu<SqlActReModel>("موتور: مدل", "table");
            AddMenu<SqlActReNotification>("موتور: اعلان", "table");
            AddMenu<SqlActReNotificationStatus>("موتور: وضعیت", "table");
            AddMenu<SqlActReProcdef>("موتور: تعریف فرایند", "table");
            AddMenu<SqlActReQuery>("موتور: پرس‌وجو", "table");
            AddMenu<SqlActReReport>("موتور: گزارش", "table");
            AddMenu<SqlActReTable>("موتور: جدول", "table");
            AddMenu<SqlActReTopic>("موتور: موضوع", "table");
            AddMenu<SqlActRuAuthorization>("موتور: مجوز", "table");
            AddMenu<SqlActRuBatch>("موتور: دسته", "table");
            AddMenu<SqlActRuCaseExecution>("موتور: اجرا", "table");
            AddMenu<SqlActRuCaseSentryPart>("موتور: بخش", "table");
            AddMenu<SqlActRuChangeQueue>("موتور: صف", "table");
            AddMenu<SqlActRuEventSubscr>("موتور: اشتراک", "table");
            AddMenu<SqlActRuExecution>("موتور: اجرا", "table");
            AddMenu<SqlActRuExtTask>("موتور: وظیفه", "table");
            AddMenu<SqlActRuFilter>("موتور: فیلتر", "table");
            AddMenu<SqlActRuIdentitylink>("موتور: پیوند هویت", "table");
            AddMenu<SqlActRuIncident>("موتور: رخداد خطا", "table");
            AddMenu<SqlActRuJob>("موتور: کار پس‌زمینه", "table");
            AddMenu<SqlActRuJobdef>("موتور: تعریف کار پس‌زمینه", "table");
            AddMenu<SqlActRuMeterLog>("موتور: سوابق", "table");
            AddMenu<SqlActRuTask>("موتور: وظیفه", "table");
            AddMenu<SqlActRuTaskMeterLog>("موتور: سوابق", "table");
            AddMenu<SqlActRuVariable>("موتور: متغیر", "table");
            AddMenu("گزارش‌ها", "chart-bar", "HyperReports6", "");
            {
                StartSubMenus();
                AddReport<SqlActGeBytearray>("گزارش موتور: داده باینری", "chart-bar");
                AddReport<SqlActGeProperty>("گزارش موتور: ویژگی", "chart-bar");
                AddReport<SqlActGeSchemaLog>("گزارش موتور: سوابق", "chart-bar");
                AddReport<SqlActHiActinst>("گزارش سوابق موتور: نمونه فعالیت", "chart-bar");
                AddReport<SqlActHiAttachment>("گزارش سوابق موتور: پیوست", "chart-bar");
                AddReport<SqlActHiBatch>("گزارش سوابق موتور: دسته", "chart-bar");
                AddReport<SqlActHiCaseactinst>("گزارش سوابق موتور: نمونه فعالیت پرونده", "chart-bar");
                AddReport<SqlActHiCaseinst>("گزارش سوابق موتور: نمونه پرونده", "chart-bar");
                AddReport<SqlActHiComment>("گزارش سوابق موتور: نظر", "chart-bar");
                AddReport<SqlActHiDecIn>("گزارش سوابق موتور: ورودی", "chart-bar");
                AddReport<SqlActHiDecOut>("گزارش سوابق موتور: خروجی", "chart-bar");
                AddReport<SqlActHiDecinst>("گزارش سوابق موتور: نمونه تصمیم", "chart-bar");
                AddReport<SqlActHiDetail>("گزارش سوابق موتور: تفصیلی", "chart-bar");
                AddReport<SqlActHiExtTaskLog>("گزارش سوابق موتور: سوابق", "chart-bar");
                AddReport<SqlActHiIdentitylink>("گزارش سوابق موتور: پیوند هویت", "chart-bar");
                AddReport<SqlActHiIncident>("گزارش سوابق موتور: رخداد خطا", "chart-bar");
                AddReport<SqlActHiJobLog>("گزارش سوابق موتور: سوابق", "chart-bar");
                AddReport<SqlActHiOpLog>("گزارش سوابق موتور: سوابق", "chart-bar");
                AddReport<SqlActHiProcinst>("گزارش سوابق موتور: نمونه فرایند", "chart-bar");
                AddReport<SqlActHiTaskinst>("گزارش سوابق موتور: نمونه وظیفه", "chart-bar");
                AddReport<SqlActHiVarinst>("گزارش سوابق موتور: نمونه متغیر", "chart-bar");
                AddReport<SqlActIdGroup>("گزارش موتور: گروه", "chart-bar");
                AddReport<SqlActIdInfo>("گزارش موتور: اطلاعات", "chart-bar");
                AddReport<SqlActIdMembership>("گزارش موتور: عضویت", "chart-bar");
                AddReport<SqlActIdRememberMe>("گزارش موتور: من", "chart-bar");
                AddReport<SqlActIdTenant>("گزارش موتور: مستاجر", "chart-bar");
                AddReport<SqlActIdTenantMember>("گزارش موتور: عضو", "chart-bar");
                AddReport<SqlActIdUser>("گزارش موتور: کاربر", "chart-bar");
                AddReport<SqlActReAssociation>("گزارش موتور: ارتباط", "chart-bar");
                AddReport<SqlActReCamformdef>("گزارش موتور: تعریف فرم موتور", "chart-bar");
                AddReport<SqlActReCaseDef>("گزارش موتور: تعریف", "chart-bar");
                AddReport<SqlActReColumn>("گزارش موتور: ستون", "chart-bar");
                AddReport<SqlActReConstraint>("گزارش موتور: محدودیت", "chart-bar");
                AddReport<SqlActReDashboard>("گزارش موتور: داشبورد", "chart-bar");
                AddReport<SqlActReDataForm>("گزارش موتور: فرم", "chart-bar");
                AddReport<SqlActReDataFormColumn>("گزارش موتور: ستون", "chart-bar");
                AddReport<SqlActReDataFormFilter>("گزارش موتور: فیلتر", "chart-bar");
                AddReport<SqlActReDataFormHeader>("گزارش موتور: سرصفحه", "chart-bar");
                AddReport<SqlActReDataFormSort>("گزارش موتور: مرتب‌سازی", "chart-bar");
                AddReport<SqlActReDataReport>("گزارش موتور: گزارش", "chart-bar");
                AddReport<SqlActReDataReportColumn>("گزارش موتور: ستون", "chart-bar");
                AddReport<SqlActReDataReportFilter>("گزارش موتور: فیلتر", "chart-bar");
                AddReport<SqlActReDataReportHeader>("گزارش موتور: سرصفحه", "chart-bar");
                AddReport<SqlActReDataReportSort>("گزارش موتور: مرتب‌سازی", "chart-bar");
                AddReport<SqlActReDecisionDef>("گزارش موتور: تعریف", "chart-bar");
                AddReport<SqlActReDecisionReqDef>("گزارش موتور: تعریف", "chart-bar");
                AddReport<SqlActReDeployment>("گزارش موتور: استقرار", "chart-bar");
                AddReport<SqlActReForm>("گزارش موتور: فرم", "chart-bar");
                AddReport<SqlActReLink>("گزارش موتور: پیوند", "chart-bar");
                AddReport<SqlActReMenu>("گزارش موتور: منو", "chart-bar");
                AddReport<SqlActReModel>("گزارش موتور: مدل", "chart-bar");
                AddReport<SqlActReNotification>("گزارش موتور: اعلان", "chart-bar");
                AddReport<SqlActReNotificationStatus>("گزارش موتور: وضعیت", "chart-bar");
                AddReport<SqlActReProcdef>("گزارش موتور: تعریف فرایند", "chart-bar");
                AddReport<SqlActReQuery>("گزارش موتور: پرس‌وجو", "chart-bar");
                AddReport<SqlActReReport>("گزارش موتور: گزارش", "chart-bar");
                AddReport<SqlActReTable>("گزارش موتور: جدول", "chart-bar");
                AddReport<SqlActReTopic>("گزارش موتور: موضوع", "chart-bar");
                AddReport<SqlActRuAuthorization>("گزارش موتور: مجوز", "chart-bar");
                AddReport<SqlActRuBatch>("گزارش موتور: دسته", "chart-bar");
                AddReport<SqlActRuCaseExecution>("گزارش موتور: اجرا", "chart-bar");
                AddReport<SqlActRuCaseSentryPart>("گزارش موتور: بخش", "chart-bar");
                AddReport<SqlActRuChangeQueue>("گزارش موتور: صف", "chart-bar");
                AddReport<SqlActRuEventSubscr>("گزارش موتور: اشتراک", "chart-bar");
                AddReport<SqlActRuExecution>("گزارش موتور: اجرا", "chart-bar");
                AddReport<SqlActRuExtTask>("گزارش موتور: وظیفه", "chart-bar");
                AddReport<SqlActRuFilter>("گزارش موتور: فیلتر", "chart-bar");
                AddReport<SqlActRuIdentitylink>("گزارش موتور: پیوند هویت", "chart-bar");
                AddReport<SqlActRuIncident>("گزارش موتور: رخداد خطا", "chart-bar");
                AddReport<SqlActRuJob>("گزارش موتور: کار پس‌زمینه", "chart-bar");
                AddReport<SqlActRuJobdef>("گزارش موتور: تعریف کار پس‌زمینه", "chart-bar");
                AddReport<SqlActRuMeterLog>("گزارش موتور: سوابق", "chart-bar");
                AddReport<SqlActRuTask>("گزارش موتور: وظیفه", "chart-bar");
                AddReport<SqlActRuTaskMeterLog>("گزارش موتور: سوابق", "chart-bar");
                AddReport<SqlActRuVariable>("گزارش موتور: متغیر", "chart-bar");
                EndSubMenus();
            }
            EndSubMenus();
        }
    }
}
