<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\Neo\src\Neo.Endpoint\Neo.Endpoint.csproj" />
    <ProjectReference Include="..\..\Core\Hyper.Application\Hyper.Application.csproj" />
    <ProjectReference Include="..\..\Core\Hyper.Infrastructure\Hyper.Infrastructure.csproj" />
    <ProjectReference Include="..\Hyper.EventHandler.Application\Hyper.EventHandler.Application.csproj" />
  </ItemGroup>

</Project>

