<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Hyper.Domain\Hyper.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\Neo\src\Neo.Application\Neo.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Messages\" />
  </ItemGroup>

</Project>


