using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using User = Hyper.Domain.Entities.Common.User;

namespace Hyper.Infrastructure.Data.Configurations;
internal class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> entity)
    {
        entity.HasKey(e => e.Id).HasName("Id");

        // UserId is an enum whose underlying type is int. EF Core does not
        // always infer identity value generation for enum-backed keys, so it
        // may otherwise include Id (0) in INSERT statements. The Users.Id
        // column is an IDENTITY column and must be generated by SQL Server.
        entity.Property(e => e.Id)
            .ValueGeneratedOnAdd();

        entity.Property(e => e.CreateDate).HasColumnType("datetime");
        entity.Property(e => e.ExpireDate).HasColumnType("datetime");
        
        // Index on Mobile for faster login lookup
        entity.HasIndex(e => e.Mobile)
            .HasDatabaseName("IX_Users_Mobile")
            .IsUnique();
    }
}
