// <auto-generated />
using Hyper.Integration.Domain.Entities.Integrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace Hyper.Infrastructure.Data.Configurations;

public sealed class ExternalIntegrationConnectionConfiguration : IEntityTypeConfiguration<ExternalIntegrationConnection>, IIntegrationEntityConfiguration
{
    public void Configure(EntityTypeBuilder<ExternalIntegrationConnection> entity)
    {
            entity.ToTable("ExternalIntegrationConnections", "dbo", table => table.ExcludeFromMigrations());
            entity.HasKey("Id").HasName("PK__External__3214EC071CF01388").IsClustered(true);
            entity.Property(e => e.Id).HasColumnName("Id").HasColumnType("bigint").IsRequired(true).UseIdentityColumn(1L, 1);
            entity.Property(e => e.ShopId).HasColumnName("ShopId").HasColumnType("int").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.TenantId).HasColumnName("TenantId").HasColumnType("nvarchar(30)").IsRequired(true).HasMaxLength(30).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.Provider).HasColumnName("Provider").HasColumnType("tinyint").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.DisplayName).HasColumnName("DisplayName").HasColumnType("nvarchar(200)").IsRequired(true).HasMaxLength(200).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.AccountIdentifier).HasColumnName("AccountIdentifier").HasColumnType("nvarchar(200)").IsRequired(true).HasMaxLength(200).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.CredentialType).HasColumnName("CredentialType").HasColumnType("tinyint").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.CredentialsJson).HasColumnName("CredentialsJson").HasColumnType("nvarchar(max)").IsRequired(true).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.ExpiresAtUtc).HasColumnName("ExpiresAtUtc").HasColumnType("datetime2(7)").IsRequired(false).ValueGeneratedNever();
            entity.Property(e => e.IsEnabled).HasColumnName("IsEnabled").HasColumnType("bit").IsRequired(true).HasDefaultValueSql("((1))", "DF__ExternalI__IsEna__70D6FD2E");
            entity.Property(e => e.ConnectedAtUtc).HasColumnName("ConnectedAtUtc").HasColumnType("datetime2(7)").IsRequired(true).HasDefaultValueSql("(sysutcdatetime())", "DF__ExternalI__Conne__71CB2167");
            entity.Property(e => e.LastSyncAtUtc).HasColumnName("LastSyncAtUtc").HasColumnType("datetime2(7)").IsRequired(false).ValueGeneratedNever();
            entity.Property(e => e.LastError).HasColumnName("LastError").HasColumnType("nvarchar(2000)").IsRequired(false).HasMaxLength(2000).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            // Keep connection identity within the shop/tenant scope used by
            // the management API and authorization.
            entity.HasAlternateKey("ShopId", "TenantId", "Provider", "AccountIdentifier").HasName("UQ_ExternalIntegrationConnections").IsClustered(false);
            entity.Property(e => e.IsEnabled).HasSentinel(true);
    }
}

