// <auto-generated />
using Hyper.Domain.Entities.Integrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace Hyper.Infrastructure.Data.Configurations;

public sealed class ExternalOrderMappingConfiguration : IEntityTypeConfiguration<ExternalOrderMapping>
{
    public void Configure(EntityTypeBuilder<ExternalOrderMapping> entity)
    {
            entity.ToTable("ExternalOrderMappings", "dbo", table => table.ExcludeFromMigrations());
            entity.HasKey("Id").HasName("PK__External__3214EC07B9DCDBBD").IsClustered(true);
            entity.Property(e => e.Id).HasColumnName("Id").HasColumnType("bigint").IsRequired(true).UseIdentityColumn(1L, 1);
            entity.Property(e => e.ConnectionId).HasColumnName("ConnectionId").HasColumnType("bigint").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.ShopId).HasColumnName("ShopId").HasColumnType("int").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.HyperSaleOrderId).HasColumnName("HyperSaleOrderId").HasColumnType("bigint").IsRequired(false).ValueGeneratedNever();
            entity.Property(e => e.ExternalOrderId).HasColumnName("ExternalOrderId").HasColumnType("nvarchar(200)").IsRequired(true).HasMaxLength(200).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.ExternalParcelId).HasColumnName("ExternalParcelId").HasColumnType("nvarchar(200)").IsRequired(false).HasMaxLength(200).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.Status).HasColumnName("Status").HasColumnType("tinyint").IsRequired(true).HasDefaultValueSql("((0))", "DF__ExternalO__Statu__07BA6286");
            entity.Property(e => e.LastSyncAtUtc).HasColumnName("LastSyncAtUtc").HasColumnType("datetime2(7)").IsRequired(false).ValueGeneratedNever();
            entity.HasAlternateKey("ConnectionId", "ExternalOrderId").HasName("UQ_ExternalOrderMappings").IsClustered(false);
    }
}