// <auto-generated />
using Hyper.Domain.Entities.Integrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace Hyper.Infrastructure.Data.Configurations;

public sealed class ExternalProductMappingConfiguration : IEntityTypeConfiguration<ExternalProductMapping>
{
    public void Configure(EntityTypeBuilder<ExternalProductMapping> entity)
    {
            entity.ToTable("ExternalProductMappings", "dbo", table => table.ExcludeFromMigrations());
            entity.HasKey("Id").HasName("PK__External__3214EC07F1E9004B").IsClustered(true);
            entity.Property(e => e.Id).HasColumnName("Id").HasColumnType("bigint").IsRequired(true).UseIdentityColumn(1L, 1);
            entity.Property(e => e.ConnectionId).HasColumnName("ConnectionId").HasColumnType("bigint").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.ShopId).HasColumnName("ShopId").HasColumnType("int").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.HyperProductId).HasColumnName("HyperProductId").HasColumnType("int").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.ExternalProductId).HasColumnName("ExternalProductId").HasColumnType("nvarchar(200)").IsRequired(true).HasMaxLength(200).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.ExternalSku).HasColumnName("ExternalSku").HasColumnType("nvarchar(200)").IsRequired(false).HasMaxLength(200).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.ExternalVariantId).HasColumnName("ExternalVariantId").HasColumnType("nvarchar(200)").IsRequired(false).HasMaxLength(200).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.LastExternalPrice).HasColumnName("LastExternalPrice").HasColumnType("decimal(18,2)").IsRequired(false).HasPrecision(18, 2).ValueGeneratedNever();
            entity.Property(e => e.LastExternalInventory).HasColumnName("LastExternalInventory").HasColumnType("decimal(18,3)").IsRequired(false).HasPrecision(18, 3).ValueGeneratedNever();
            entity.Property(e => e.LastSyncAtUtc).HasColumnName("LastSyncAtUtc").HasColumnType("datetime2(7)").IsRequired(false).ValueGeneratedNever();
            entity.Property(e => e.IsActive).HasColumnName("IsActive").HasColumnType("bit").IsRequired(true).HasDefaultValueSql("((1))", "DF__ExternalP__IsAct__759BB24B");
            entity.HasIndex(new[] { "ConnectionId", "ExternalProductId", "ExternalVariantId" }, "UQ_ExternalProductMappings").IsUnique(true).IsClustered(false).HasFilter(null).IsDescending(false, false, false).HasAnnotation("Hyper:DatabaseUniqueConstraint", true);
            entity.HasOne<ExternalIntegrationConnection>().WithMany().HasForeignKey("ConnectionId").OnDelete(DeleteBehavior.NoAction).HasConstraintName("FK_ExternalProductMappings_Connection");
            entity.Property(e => e.IsActive).HasSentinel(true);
    }
}