// <auto-generated />
using Hyper.Integration.Domain.Entities.Integrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace Hyper.Infrastructure.Data.Configurations;

public sealed class IntegrationTokenRequestConfiguration : IEntityTypeConfiguration<IntegrationTokenRequest>, IIntegrationEntityConfiguration
{
    public void Configure(EntityTypeBuilder<IntegrationTokenRequest> entity)
    {
            entity.ToTable("IntegrationTokenRequests", "dbo", table => table.ExcludeFromMigrations());
            entity.HasKey("Id").HasName("PK_IntegrationTokenRequests").IsClustered(true);
            entity.Property(e => e.Id).HasColumnName("Id").HasColumnType("uniqueidentifier").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.SimulationId).HasColumnName("SimulationId").HasColumnType("uniqueidentifier").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.Provider).HasColumnName("Provider").HasColumnType("tinyint").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.CredentialType).HasColumnName("CredentialType").HasColumnType("tinyint").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.Status).HasColumnName("Status").HasColumnType("tinyint").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.RequestedAtUtc).HasColumnName("RequestedAtUtc").HasColumnType("datetime2(7)").IsRequired(true).ValueGeneratedNever();
            entity.HasOne<IntegrationAdminSimulation>().WithMany().HasForeignKey("SimulationId").OnDelete(DeleteBehavior.NoAction).HasConstraintName("FK_IntegrationTokenRequests_Simulation");
    }
}

