// <auto-generated />
using Hyper.Domain.Entities.Integrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace Hyper.Infrastructure.Data.Configurations;

public sealed class IntegrationWebhookInboxConfiguration : IEntityTypeConfiguration<IntegrationWebhookInbox>
{
    public void Configure(EntityTypeBuilder<IntegrationWebhookInbox> entity)
    {
            entity.ToTable("IntegrationWebhookInbox", "dbo", table => table.ExcludeFromMigrations());
            entity.HasKey("Id").HasName("PK__Integrat__3214EC07AA3DFE97").IsClustered(true);
            entity.Property(e => e.Id).HasColumnName("Id").HasColumnType("bigint").IsRequired(true).UseIdentityColumn(1L, 1);
            entity.Property(e => e.ConnectionId).HasColumnName("ConnectionId").HasColumnType("bigint").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.ExternalEventId).HasColumnName("ExternalEventId").HasColumnType("nvarchar(200)").IsRequired(true).HasMaxLength(200).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.EventType).HasColumnName("EventType").HasColumnType("nvarchar(200)").IsRequired(true).HasMaxLength(200).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.PayloadJson).HasColumnName("PayloadJson").HasColumnType("nvarchar(max)").IsRequired(true).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.ReceivedAtUtc).HasColumnName("ReceivedAtUtc").HasColumnType("datetime2(7)").IsRequired(true).HasDefaultValueSql("(sysutcdatetime())", "DF__Integrati__Recei__02018930");
            entity.Property(e => e.ProcessedAtUtc).HasColumnName("ProcessedAtUtc").HasColumnType("datetime2(7)").IsRequired(false).ValueGeneratedNever();
            entity.Property(e => e.Status).HasColumnName("Status").HasColumnType("tinyint").IsRequired(true).HasDefaultValueSql("((0))", "DF__Integrati__Statu__02F5AD69");
            entity.Property(e => e.Error).HasColumnName("Error").HasColumnType("nvarchar(4000)").IsRequired(false).HasMaxLength(4000).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.HasAlternateKey("ConnectionId", "ExternalEventId").HasName("UQ_IntegrationWebhookInbox").IsClustered(false);
            entity.HasOne<ExternalIntegrationConnection>().WithMany().HasForeignKey("ConnectionId").OnDelete(DeleteBehavior.NoAction).HasConstraintName("FK_IntegrationWebhookInbox_Connection");
    }
}