// <auto-generated />
using Hyper.Domain.Entities.Integrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace Hyper.Infrastructure.Data.Configurations;

public sealed class IntegrationAdminSimulationConfiguration : IEntityTypeConfiguration<IntegrationAdminSimulation>
{
    public void Configure(EntityTypeBuilder<IntegrationAdminSimulation> entity)
    {
            entity.ToTable("IntegrationAdminSimulations", "dbo", table => table.ExcludeFromMigrations());
            entity.HasKey("Id").HasName("PK_IntegrationAdminSimulations").IsClustered(true);
            entity.Property(e => e.Id).HasColumnName("Id").HasColumnType("uniqueidentifier").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.AdminUserId).HasColumnName("AdminUserId").HasColumnType("nvarchar(128)").IsRequired(true).HasMaxLength(128).IsUnicode(true).UseCollation("Latin1_General_100_BIN2").ValueGeneratedNever();
            entity.Property(e => e.ShopId).HasColumnName("ShopId").HasColumnType("int").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.MerchantIdentifier).HasColumnName("MerchantIdentifier").HasColumnType("nvarchar(128)").IsRequired(true).HasMaxLength(128).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.TenantId).HasColumnName("TenantId").HasColumnType("nvarchar(30)").IsRequired(true).HasMaxLength(30).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.ShopName).HasColumnName("ShopName").HasColumnType("nvarchar(400)").IsRequired(true).HasMaxLength(400).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.CreatedAtUtc).HasColumnName("CreatedAtUtc").HasColumnType("datetime2(7)").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.ExpiresAtUtc).HasColumnName("ExpiresAtUtc").HasColumnType("datetime2(7)").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.EndedAtUtc).HasColumnName("EndedAtUtc").HasColumnType("datetime2(7)").IsRequired(false).ValueGeneratedNever();
    }
}