// <auto-generated />
using Hyper.Integration.Domain.Entities.Integrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace Hyper.Infrastructure.Data.Configurations;

public sealed class IntegrationOutboxMessageConfiguration : IEntityTypeConfiguration<IntegrationOutboxMessage>, IIntegrationEntityConfiguration
{
    public void Configure(EntityTypeBuilder<IntegrationOutboxMessage> entity)
    {
            entity.ToTable("IntegrationOutbox", "dbo", table => table.ExcludeFromMigrations());
            entity.HasKey("Id").HasName("PK_IntegrationOutbox").IsClustered(true);
            entity.Property(e => e.Id).HasColumnName("Id").HasColumnType("bigint").IsRequired(true).UseIdentityColumn(1L, 1);
            entity.Property(e => e.ConnectionId).HasColumnName("ConnectionId").HasColumnType("bigint").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.MappingId).HasColumnName("MappingId").HasColumnType("bigint").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.SourceVersion).HasColumnName("SourceVersion").HasColumnType("bigint").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.Operation).HasColumnName("Operation").HasColumnType("nvarchar(60)").IsRequired(true).HasMaxLength(60).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.PayloadJson).HasColumnName("PayloadJson").HasColumnType("nvarchar(max)").IsRequired(true).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.Status).HasColumnName("Status").HasColumnType("tinyint").IsRequired(true).HasDefaultValueSql("((0))", "DF_IntegrationOutbox_Status");
            entity.Property(e => e.Attempts).HasColumnName("Attempts").HasColumnType("int").IsRequired(true).HasDefaultValueSql("((0))", "DF_IntegrationOutbox_Attempts");
            entity.Property(e => e.CreatedAtUtc).HasColumnName("CreatedAtUtc").HasColumnType("datetime2(7)").IsRequired(true).HasDefaultValueSql("(sysutcdatetime())", "DF_IntegrationOutbox_Created");
            entity.Property(e => e.NextAttemptAtUtc).HasColumnName("NextAttemptAtUtc").HasColumnType("datetime2(7)").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.LeaseId).HasColumnName("LeaseId").HasColumnType("uniqueidentifier").IsRequired(false).ValueGeneratedNever();
            entity.Property(e => e.LeaseExpiresAtUtc).HasColumnName("LeaseExpiresAtUtc").HasColumnType("datetime2(7)").IsRequired(false).ValueGeneratedNever();
            entity.Property(e => e.CompletedAtUtc).HasColumnName("CompletedAtUtc").HasColumnType("datetime2(7)").IsRequired(false).ValueGeneratedNever();
            entity.Property(e => e.LastError).HasColumnName("LastError").HasColumnType("nvarchar(200)").IsRequired(false).HasMaxLength(200).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.HasIndex(new[] { "MappingId", "SourceVersion" }, "UX_IntegrationOutbox_Source").IsUnique(true).IsClustered(false).HasFilter(null).IsDescending(false, false);
            entity.HasIndex(new[] { "Status", "NextAttemptAtUtc", "ConnectionId" }, "IX_IntegrationOutbox_Due").IsUnique(false).IsClustered(false).HasFilter(null).IsDescending(false, false, false);
            entity.HasIndex(new[] { "ConnectionId", "Id" }, "IX_IntegrationOutbox_Connection").IsUnique(false).IsClustered(false).HasFilter(null).IsDescending(false, false);
            entity.HasOne<ExternalIntegrationConnection>().WithMany().HasForeignKey("ConnectionId").OnDelete(DeleteBehavior.NoAction).HasConstraintName("FK_IntegrationOutbox_Connection");
            entity.HasOne<ExternalProductMapping>().WithMany().HasForeignKey("MappingId").OnDelete(DeleteBehavior.NoAction).HasConstraintName("FK_IntegrationOutbox_Mapping");
    }
}

