// <auto-generated />
using Hyper.Domain.Entities.Integrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace Hyper.Infrastructure.Data.Configurations;

public sealed class IntegrationEventAuditConfiguration : IEntityTypeConfiguration<IntegrationEventAudit>
{
    public void Configure(EntityTypeBuilder<IntegrationEventAudit> entity)
    {
            entity.ToTable("IntegrationEventAudits", "dbo", table => table.ExcludeFromMigrations());
            entity.HasKey("Id").HasName("PK__Integrat__3214EC0756BD0147").IsClustered(true);
            entity.Property(e => e.Id).HasColumnName("Id").HasColumnType("bigint").IsRequired(true).UseIdentityColumn(1L, 1);
            entity.Property(e => e.ConnectionId).HasColumnName("ConnectionId").HasColumnType("bigint").IsRequired(false).ValueGeneratedNever();
            entity.Property(e => e.Direction).HasColumnName("Direction").HasColumnType("varchar(20)").IsRequired(true).HasMaxLength(20).IsUnicode(false).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.EventType).HasColumnName("EventType").HasColumnType("nvarchar(200)").IsRequired(true).HasMaxLength(200).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.ExternalEventId).HasColumnName("ExternalEventId").HasColumnType("nvarchar(200)").IsRequired(true).HasMaxLength(200).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.PayloadHash).HasColumnName("PayloadHash").HasColumnType("varchar(128)").IsRequired(true).HasMaxLength(128).IsUnicode(false).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.SignatureValid).HasColumnName("SignatureValid").HasColumnType("bit").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.CorrelationId).HasColumnName("CorrelationId").HasColumnType("varchar(100)").IsRequired(false).HasMaxLength(100).IsUnicode(false).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.ReceivedAtUtc).HasColumnName("ReceivedAtUtc").HasColumnType("datetime2(7)").IsRequired(true).HasDefaultValueSql("(sysutcdatetime())", "DF__Integrati__Recei__104FA887");
            entity.HasIndex(new[] { "ConnectionId", "ExternalEventId", "Direction" }, "UQ_IntegrationEventAudits").IsUnique(true).IsClustered(false).HasFilter(null).IsDescending(false, false, false).HasAnnotation("Hyper:DatabaseUniqueConstraint", true);
    }
}