// <auto-generated />
using Hyper.Domain.Entities.Integrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace Hyper.Infrastructure.Data.Configurations;

public sealed class IntegrationMerchantAccessConfiguration : IEntityTypeConfiguration<IntegrationMerchantAccess>
{
    public void Configure(EntityTypeBuilder<IntegrationMerchantAccess> entity)
    {
            entity.ToTable("IntegrationMerchantAccess", "dbo", table => table.ExcludeFromMigrations());
            entity.HasKey("Id").HasName("PK_IntegrationMerchantAccess").IsClustered(true);
            entity.Property(e => e.Id).HasColumnName("Id").HasColumnType("bigint").IsRequired(true).UseIdentityColumn(1L, 1);
            entity.Property(e => e.Issuer).HasColumnName("Issuer").HasColumnType("nvarchar(300)").IsRequired(true).HasMaxLength(300).IsUnicode(true).UseCollation("Latin1_General_100_BIN2").ValueGeneratedNever();
            entity.Property(e => e.SubjectId).HasColumnName("SubjectId").HasColumnType("nvarchar(128)").IsRequired(true).HasMaxLength(128).IsUnicode(true).UseCollation("Latin1_General_100_BIN2").ValueGeneratedNever();
            entity.Property(e => e.ShopId).HasColumnName("ShopId").HasColumnType("int").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.IsEnabled).HasColumnName("IsEnabled").HasColumnType("bit").IsRequired(true).HasDefaultValueSql("((1))", "DF_IntegrationMerchantAccess_Enabled");
            entity.Property(e => e.CreatedAtUtc).HasColumnName("CreatedAtUtc").HasColumnType("datetime2(7)").IsRequired(true).HasDefaultValueSql("(sysutcdatetime())", "DF_IntegrationMerchantAccess_Created");
            entity.Property(e => e.CreatedBy).HasColumnName("CreatedBy").HasColumnType("nvarchar(128)").IsRequired(true).HasMaxLength(128).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.ExpiresAtUtc).HasColumnName("ExpiresAtUtc").HasColumnType("datetime2(7)").IsRequired(false).ValueGeneratedNever();
            entity.Property(e => e.RevokedAtUtc).HasColumnName("RevokedAtUtc").HasColumnType("datetime2(7)").IsRequired(false).ValueGeneratedNever();
            entity.HasAlternateKey("Issuer", "SubjectId", "ShopId").HasName("UQ_IntegrationMerchantAccess_IdentityShop").IsClustered(false);
            entity.Property(e => e.IsEnabled).HasSentinel(true);
    }
}