// <auto-generated />
using Hyper.Integration.Domain.Entities.Integrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace Hyper.Infrastructure.Data.Configurations;

public sealed class IntegrationSyncRunConfiguration : IEntityTypeConfiguration<IntegrationSyncRun>, IIntegrationEntityConfiguration
{
    public void Configure(EntityTypeBuilder<IntegrationSyncRun> entity)
    {
            entity.ToTable("IntegrationSyncRuns", "dbo", table => table.ExcludeFromMigrations());
            entity.HasKey("Id").HasName("PK__Integrat__3214EC071F6D152D").IsClustered(true);
            entity.Property(e => e.Id).HasColumnName("Id").HasColumnType("bigint").IsRequired(true).UseIdentityColumn(1L, 1);
            entity.Property(e => e.ConnectionId).HasColumnName("ConnectionId").HasColumnType("bigint").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.StartedAtUtc).HasColumnName("StartedAtUtc").HasColumnType("datetime2(7)").IsRequired(true).HasDefaultValueSql("(sysutcdatetime())", "DF__Integrati__Start__796C432F");
            entity.Property(e => e.FinishedAtUtc).HasColumnName("FinishedAtUtc").HasColumnType("datetime2(7)").IsRequired(false).ValueGeneratedNever();
            entity.Property(e => e.Status).HasColumnName("Status").HasColumnType("tinyint").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.ItemsRead).HasColumnName("ItemsRead").HasColumnType("int").IsRequired(true).HasDefaultValueSql("((0))", "DF__Integrati__Items__7A606768");
            entity.Property(e => e.ItemsWritten).HasColumnName("ItemsWritten").HasColumnType("int").IsRequired(true).HasDefaultValueSql("((0))", "DF__Integrati__Items__7B548BA1");
            entity.Property(e => e.ItemsFailed).HasColumnName("ItemsFailed").HasColumnType("int").IsRequired(true).HasDefaultValueSql("((0))", "DF__Integrati__Items__7C48AFDA");
            entity.Property(e => e.Error).HasColumnName("Error").HasColumnType("nvarchar(4000)").IsRequired(false).HasMaxLength(4000).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.HasOne<ExternalIntegrationConnection>().WithMany().HasForeignKey("ConnectionId").OnDelete(DeleteBehavior.NoAction).HasConstraintName("FK_IntegrationSyncRuns_Connection");
    }
}

