// <auto-generated />
using Hyper.Domain.Entities.Integrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace Hyper.Infrastructure.Data.Configurations;

public sealed class InventoryReservationLogConfiguration : IEntityTypeConfiguration<InventoryReservationLog>
{
    public void Configure(EntityTypeBuilder<InventoryReservationLog> entity)
    {
            entity.ToTable("InventoryReservationLogs", "dbo", table => table.ExcludeFromMigrations());
            entity.HasKey("Id").HasName("PK__Inventor__3214EC0779CA3480").IsClustered(true);
            entity.Property(e => e.Id).HasColumnName("Id").HasColumnType("bigint").IsRequired(true).UseIdentityColumn(1L, 1);
            entity.Property(e => e.ShopId).HasColumnName("ShopId").HasColumnType("int").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.HyperProductId).HasColumnName("HyperProductId").HasColumnType("int").IsRequired(true).ValueGeneratedNever();
            entity.Property(e => e.ReservationKey).HasColumnName("ReservationKey").HasColumnType("nvarchar(200)").IsRequired(true).HasMaxLength(200).IsUnicode(true).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.Quantity).HasColumnName("Quantity").HasColumnType("decimal(18,3)").IsRequired(true).HasPrecision(18, 3).ValueGeneratedNever();
            entity.Property(e => e.Status).HasColumnName("Status").HasColumnType("tinyint").IsRequired(true).HasDefaultValueSql("((0))", "DF__Inventory__Statu__0B8AF36A");
            entity.Property(e => e.Source).HasColumnName("Source").HasColumnType("varchar(50)").IsRequired(true).HasMaxLength(50).IsUnicode(false).UseCollation("SQL_Latin1_General_CP1_CI_AS").ValueGeneratedNever();
            entity.Property(e => e.CreatedAtUtc).HasColumnName("CreatedAtUtc").HasColumnType("datetime2(7)").IsRequired(true).HasDefaultValueSql("(sysutcdatetime())", "DF__Inventory__Creat__0C7F17A3");
            entity.Property(e => e.ReleasedAtUtc).HasColumnName("ReleasedAtUtc").HasColumnType("datetime2(7)").IsRequired(false).ValueGeneratedNever();
            entity.HasAlternateKey("ShopId", "ReservationKey").HasName("UQ_InventoryReservationLogs").IsClustered(false);
    }
}