using System.Text.Json; using System.Security.Cryptography; using System.Text;
using Hyper.Domain.Entities.Integrations;
using Hyper.Domain.Features.Integrations;
using Hyper.Infrastructure.Data.Repository.Hyper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace Hyper.CustomerPortal.Api.Controllers;
[AppRoute("Hyper","integrations")][ApiController][Authorize]
public sealed class IntegrationsController(HyperContextCommand db,IIntegrationSynchronizationService sync) : ControllerBase
{
 [HttpGet("providers")] public IActionResult Providers()=>Ok(Enum.GetValues<IntegrationProvider>().Select(x=>new {Value=(byte)x,Name=x.ToString()}));
 [HttpGet("connections")] public async Task<IActionResult> Connections(CancellationToken ct)=>Ok(await db.ExternalIntegrationConnections.AsNoTracking().Select(x=>new{x.Id,x.ShopId,x.TenantId,x.Provider,x.DisplayName,x.AccountIdentifier,x.CredentialType,x.IsEnabled,x.LastSyncAtUtc,x.LastError}).ToListAsync(ct));
 [HttpPost("connections")] public async Task<IActionResult> Register([FromBody] RegisterConnectionRequest request,CancellationToken ct){if(request.ShopId<=0||string.IsNullOrWhiteSpace(request.TenantId)||string.IsNullOrWhiteSpace(request.AccountIdentifier)||string.IsNullOrWhiteSpace(request.CredentialsJson))return BadRequest("shop, tenant, account and credentials are required");if(!Enum.IsDefined(request.Provider)||!Enum.IsDefined(request.CredentialType))return BadRequest("unsupported provider or credential type");if(await db.ExternalIntegrationConnections.AnyAsync(x=>x.ShopId==request.ShopId&&x.Provider==request.Provider&&x.AccountIdentifier==request.AccountIdentifier,ct))return Conflict("connection already exists");var entity=new ExternalIntegrationConnection{ShopId=request.ShopId,TenantId=request.TenantId,Provider=request.Provider,DisplayName=request.DisplayName,AccountIdentifier=request.AccountIdentifier,CredentialType=request.CredentialType,CredentialsJson=request.CredentialsJson};db.ExternalIntegrationConnections.Add(entity);await db.SaveChangesAsync(ct);return Created($"connections/{entity.Id}",new {entity.Id,entity.Provider,entity.DisplayName,entity.AccountIdentifier,entity.IsEnabled});}
 [HttpPost("connections/{id:long}/disable")] public async Task<IActionResult> Disable(long id,CancellationToken ct){var x=await db.ExternalIntegrationConnections.FindAsync([id],ct);if(x is null)return NotFound();x.IsEnabled=false;await db.SaveChangesAsync(ct);return NoContent();}
 [HttpGet("connections/{id:long}/webhooks")] public async Task<IActionResult> Webhooks(long id,[FromQuery] byte? status,CancellationToken ct){var q=db.IntegrationWebhookInbox.AsNoTracking().Where(x=>x.ConnectionId==id);if(status.HasValue)q=q.Where(x=>x.Status==status.Value);return Ok(await q.OrderByDescending(x=>x.ReceivedAtUtc).Take(200).Select(x=>new{x.Id,x.ExternalEventId,x.EventType,x.ReceivedAtUtc,x.ProcessedAtUtc,x.Status,x.Error}).ToListAsync(ct));} [HttpPost("webhooks/{webhookId:long}/replay")] public async Task<IActionResult> Replay(long webhookId,CancellationToken ct){var x=await db.IntegrationWebhookInbox.SingleOrDefaultAsync(x=>x.Id==webhookId,ct);if(x is null)return NotFound();x.Status=0;x.Error=null;x.ProcessedAtUtc=null;await db.SaveChangesAsync(ct);return Accepted(new{WebhookId=x.Id,Queued=true});} [HttpGet("connections/{id:long}/mappings")] public async Task<IActionResult> Mappings(long id,CancellationToken ct)=>Ok(await db.ExternalProductMappings.AsNoTracking().Where(x=>x.ConnectionId==id).ToListAsync(ct)); [HttpGet("connections/{id:long}/runs")] public async Task<IActionResult> Runs(long id,CancellationToken ct)=>Ok(await db.IntegrationSyncRuns.AsNoTracking().Where(x=>x.ConnectionId==id).OrderByDescending(x=>x.StartedAtUtc).Take(100).ToListAsync(ct)); [HttpPost("connections/{id:long}/sync")] public async Task<IActionResult> Sync(long id,CancellationToken ct)=>Ok(new{RunId=await sync.SynchronizeAsync(id,ct)});
 [AllowAnonymous][HttpPost("webhooks/{id:long}")] public async Task<IActionResult> Webhook(long id,[FromHeader(Name="X-Event-Id")] string eventId,[FromHeader(Name="X-Event-Type")] string eventType,[FromHeader(Name="X-Signature")] string? signature,[FromHeader(Name="X-Timestamp")] long? timestamp,[FromHeader(Name="X-Correlation-ID")] string? correlationId,[FromBody] JsonElement payload,CancellationToken ct){if(string.IsNullOrWhiteSpace(eventId))return BadRequest("X-Event-Id required");var connection=await db.ExternalIntegrationConnections.SingleOrDefaultAsync(x=>x.Id==id&&x.IsEnabled,ct);if(connection is null)return NotFound(); var raw=payload.GetRawText(); using var sha=SHA256.Create(); var payloadHash=Convert.ToHexString(sha.ComputeHash(Encoding.UTF8.GetBytes(raw))); if(timestamp.HasValue && Math.Abs(DateTimeOffset.UtcNow.ToUnixTimeSeconds()-timestamp.Value)>300)return Unauthorized("timestamp expired");if(!string.IsNullOrWhiteSpace(signature)){try{using var doc=JsonDocument.Parse(connection.CredentialsJson);if(!doc.RootElement.TryGetProperty("webhookSecret",out var secret)||string.IsNullOrWhiteSpace(secret.GetString()))return Unauthorized();{var body=raw;using var h= new HMACSHA256(Encoding.UTF8.GetBytes(secret.GetString()!));var expected=Convert.ToHexString(h.ComputeHash(Encoding.UTF8.GetBytes(body)));if(!CryptographicOperations.FixedTimeEquals(Encoding.UTF8.GetBytes(expected.ToLowerInvariant()),Encoding.UTF8.GetBytes(signature.Trim().ToLowerInvariant())))return Unauthorized();}}catch(JsonException){return BadRequest("invalid credentials");}}else return Unauthorized(); db.IntegrationEventAudits.Add(new IntegrationEventAudit{ConnectionId=id,Direction="Inbound",EventType=eventType??"unknown",ExternalEventId=eventId,PayloadHash=payloadHash,SignatureValid=true,CorrelationId=correlationId}); if(await db.IntegrationWebhookInbox.AnyAsync(x=>x.ConnectionId==id&&x.ExternalEventId==eventId,ct))return Ok(new{duplicate=true});db.IntegrationWebhookInbox.Add(new IntegrationWebhookInbox{ConnectionId=id,ExternalEventId=eventId,EventType=eventType??"unknown",PayloadJson=payload.GetRawText()});await db.SaveChangesAsync(ct);return Accepted();}
 public sealed record RegisterConnectionRequest(int ShopId,string TenantId,IntegrationProvider Provider,string DisplayName,string AccountIdentifier,IntegrationCredentialType CredentialType,string CredentialsJson);
}