"""Generate database-owned Neo records and EF mappings from an audited SQL metadata snapshot.

Usage: python scripts/generate_sqlserver_model.py ../docs/schema/hyper-schema.json
No SQL connections, migrations or credentials are used by this generator.
"""
import collections
import json
import pathlib
import re
import sys

root = pathlib.Path(__file__).resolve().parents[1]
schema = json.loads(pathlib.Path(sys.argv[1]).read_text(encoding="utf-8-sig"))
objects = {o["object_id"]: o for o in schema["objects"]}
columns = collections.defaultdict(list)
indexes = collections.defaultdict(lambda: collections.defaultdict(list))
foreign_keys = collections.defaultdict(lambda: collections.defaultdict(list))
for c in schema["columns"]:
    columns[c["object_id"]].append(c)
for i in schema["indexes"]:
    indexes[i["object_id"]][i["index_id"]].append(i)
for f in schema["foreignKeys"]:
    foreign_keys[f["parent_object_id"]][f["name"]].append(f)


def name(value):
    return "".join(p[:1].upper() + p[1:].lower() for p in re.split(r"[^A-Za-z0-9]+", value) if p)


def quote(value):
    return json.dumps(value, ensure_ascii=False)


def classname(obj):
    return "Sql" + (name(obj["schema"]) if obj["schema"] != "dbo" else "") + name(obj["name"])


def clr(c):
    types = {"int": "int", "bigint": "long", "smallint": "short", "tinyint": "byte", "bit": "bool",
             "decimal": "decimal", "numeric": "decimal", "money": "decimal", "smallmoney": "decimal",
             "float": "double", "real": "float", "date": "DateOnly", "datetime": "DateTime",
             "datetime2": "DateTime", "smalldatetime": "DateTime", "datetimeoffset": "DateTimeOffset",
             "time": "TimeSpan", "uniqueidentifier": "Guid", "binary": "byte[]", "varbinary": "byte[]",
             "image": "byte[]", "timestamp": "byte[]", "rowversion": "byte[]",
             "varchar": "string", "nvarchar": "string", "char": "string", "nchar": "string",
             "text": "string", "ntext": "string", "xml": "string"}
    if c["sql_type"] not in types:
        raise ValueError(f"Unsupported SQL type: {c['sql_type']}")
    return types[c["sql_type"]] + ("?" if c["is_nullable"] else "")


def storetype(c):
    t = c["sql_type"]
    if t in ("char", "nchar", "varchar", "nvarchar", "binary", "varbinary"):
        length = "max" if c["max_length"] == -1 else str(c["max_length"] // (2 if t.startswith("n") else 1))
        return f"{t}({length})"
    if t in ("decimal", "numeric"):
        return f"{t}({c['precision']},{c['scale']})"
    if t in ("datetime2", "datetimeoffset", "time"):
        return f"{t}({c['scale']})"
    return t


def col(oid, cid):
    return next(c for c in columns[oid] if c["column_id"] == cid)


def props(oid, rows):
    return ", ".join(quote(name(col(oid, r["column_id"])["name"])) for r in sorted(rows, key=lambda r: r["key_ordinal"]))


entities = ["// <auto-generated />", "#nullable enable", "namespace Hyper.Domain.Entities.Database;", ""]
config = ["// <auto-generated />", "#nullable enable", "using Hyper.Domain.Entities.Database;",
          "using Microsoft.EntityFrameworkCore;", "namespace Hyper.Infrastructure.Data.Repository.Hyper;", "",
          "internal static class HyperSqlServerModel", "{", "    public static void Configure(ModelBuilder modelBuilder)", "    {"]
context = ["// <auto-generated />", "using Hyper.Domain.Entities.Database;", "using Microsoft.EntityFrameworkCore;",
           "using Microsoft.EntityFrameworkCore.Metadata.Conventions;", "namespace Hyper.Infrastructure.Data.Repository.Hyper;", "",
           "/// <summary>Database-owned accounting schema. Existing tables are excluded from migrations.</summary>",
           "public sealed class HyperSqlServerContext(DbContextOptions<HyperSqlServerContext> options) : DbContext(options)", "{",
           "    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)", "    {",
           "        base.ConfigureConventions(configurationBuilder);",
           "        configurationBuilder.Conventions.Remove(typeof(ForeignKeyIndexConvention));", "    }", "",
           "    protected override void OnModelCreating(ModelBuilder modelBuilder)", "    {",
           "        base.OnModelCreating(modelBuilder);", "        HyperSqlServerModel.Configure(modelBuilder);", "    }", ""]
warnings = []
integration_types = {
    "IntegrationOutbox": "IntegrationOutboxMessage",
    "IntegrationMerchantAccess": "IntegrationMerchantAccess",
    "IntegrationAdminSimulations": "IntegrationAdminSimulation",
    "IntegrationTokenRequests": "IntegrationTokenRequest",
    "ExternalIntegrationConnections": "ExternalIntegrationConnection",
    "ExternalProductMappings": "ExternalProductMapping",
    "IntegrationSyncRuns": "IntegrationSyncRun",
    "IntegrationWebhookInbox": "IntegrationWebhookInbox",
    "ExternalOrderMappings": "ExternalOrderMapping",
    "InventoryReservationLogs": "InventoryReservationLog",
    "IntegrationEventAudits": "IntegrationEventAudit",
}
integration_blocks = {}
seen = set()
for oid, obj in objects.items():
    cls = classname(obj)
    assert cls not in seen, f"Class collision: {cls}"
    seen.add(cls)
    names = [name(c["name"]) for c in columns[oid]]
    assert len(names) == len(set(names)), f"Column collision: {cls}"
    pk = [i for rows in indexes[oid].values() for i in rows if i["is_primary_key"]]
    typed = len(pk) == 1 and name(col(oid, pk[0]["column_id"])["name"]) == "Id"
    base = f"SqlServerEntity<{clr(col(oid, pk[0]['column_id']))}>" if typed else "SqlServerEntity"
    entities += [f"public sealed class {cls} : {base}", "{"]
    for c in columns[oid]:
        if typed and name(c["name"]) == "Id":
            continue
        t = clr(c)
        initializer = " = null!;" if t in ("string", "byte[]") else ""
        entities.append(f"    public {t} {name(c['name'])} {{ get; set; }}{initializer}")
    entities += ["}", ""]
    context.append(f"    public DbSet<{cls}> {cls[3:]}s => Set<{cls}>();")
    block_start = len(config)
    config += [f"        modelBuilder.Entity<{cls}>(entity =>", "        {"]
    if obj["type"].strip() == "V":
        config.append(f"            entity.ToView({quote(obj['name'])}, {quote(obj['schema'])});")
    else:
        config.append(f"            entity.ToTable({quote(obj['name'])}, {quote(obj['schema'])}, table => table.ExcludeFromMigrations());")
    if pk:
        config.append(f"            entity.HasKey({props(oid, pk)}).HasName({quote(pk[0]['name'])}).IsClustered({str(pk[0]['type'] == 1).lower()});")
    else:
        config.append("            entity.HasNoKey();")
    for c in columns[oid]:
        line = f"            entity.Property(e => e.{name(c['name'])}).HasColumnName({quote(c['name'])}).HasColumnType({quote(storetype(c))}).IsRequired({str(not c['is_nullable']).lower()})"
        if c["sql_type"] in ("char", "nchar", "varchar", "nvarchar", "binary", "varbinary") and c["max_length"] != -1:
            line += f".HasMaxLength({c['max_length'] // (2 if c['sql_type'].startswith('n') else 1)})"
        if c["sql_type"] in ("char", "nchar", "varchar", "nvarchar", "text", "ntext"):
            line += f".IsUnicode({str(c['sql_type'].startswith('n')).lower()})"
            if c["collation_name"]:
                line += f".UseCollation({quote(c['collation_name'])})"
        if c["sql_type"] in ("char", "nchar", "binary"):
            line += ".IsFixedLength()"
        if c["sql_type"] in ("numeric", "decimal"):
            line += f".HasPrecision({c['precision']}, {c['scale']})"
        if c["is_identity"]:
            line += f".UseIdentityColumn({c['identity_seed']}L, {c['identity_increment']})"
        elif c["is_computed"]:
            line += f".HasComputedColumnSql({quote(c['computed_sql'])}, stored: {str(bool(c['is_persisted'])).lower()})"
        elif c["sql_type"] in ("rowversion", "timestamp"):
            line += ".IsRowVersion()"
        elif c["default_sql"] is not None:
            line += f".HasDefaultValueSql({quote(c['default_sql'])}, {quote(c['default_name'])})"
        else:
            line += ".ValueGeneratedNever()"
        config.append(line + ";")
    for rows in indexes[oid].values():
        i = rows[0]
        if i["is_primary_key"]:
            continue
        keys = [r for r in rows if r["key_ordinal"] > 0 and not r["is_included_column"]]
        nullable = any(col(oid, r["column_id"])["is_nullable"] for r in keys)
        if i["is_unique_constraint"] and not nullable and pk:
            config.append(f"            entity.HasAlternateKey({props(oid, keys)}).HasName({quote(i['name'])}).IsClustered({str(i['type']==1).lower()});")
        else:
            line = f"            entity.HasIndex(new[] {{ {props(oid, keys)} }}, {quote(i['name'])}).IsUnique({str(i['is_unique']).lower()}).IsClustered({str(i['type']==1).lower()}).HasFilter({quote(i['filter_definition']) if i['filter_definition'] is not None else 'null'})"
            line += ".IsDescending(" + ", ".join(str(r["is_descending_key"]).lower() for r in sorted(keys, key=lambda r:r["key_ordinal"])) + ")"
            included = [r for r in rows if r["is_included_column"]]
            if included:
                line += ".IncludeProperties(" + ", ".join(quote(name(col(oid, r["column_id"])["name"])) for r in included) + ")"
            if i["is_unique_constraint"]:
                line += '.HasAnnotation("Hyper:DatabaseUniqueConstraint", true)'
                warnings.append(f"{obj['schema']}.{obj['name']}.{i['name']}: represented as unique index because EF alternate keys require nonnullable properties and a keyed entity; database constraint is unchanged.")
            config.append(line + ";")
    config += ["        });", ""]
    if obj["name"] in integration_types:
        integration_blocks[oid] = config[block_start + 2:-2].copy()

for oid, groups in foreign_keys.items():
    for fkname, rows in groups.items():
        rows.sort(key=lambda r:r["constraint_column_id"])
        principal = rows[0]["referenced_object_id"]
        delete = {"NO_ACTION":"NoAction", "CASCADE":"Cascade", "SET_NULL":"SetNull"}.get(rows[0]["delete_referential_action_desc"])
        if delete is None:
            raise ValueError(f"Unsupported delete action {fkname}")
        fprops = ", ".join(quote(name(col(oid,r["parent_column_id"])["name"])) for r in rows)
        pprops = ", ".join(quote(name(col(principal,r["referenced_column_id"])["name"])) for r in rows)
        config.append(f"        modelBuilder.Entity<{classname(objects[oid])}>().HasOne<{classname(objects[principal])}>().WithMany().HasForeignKey({fprops}).HasPrincipalKey({pprops}).OnDelete(DeleteBehavior.{delete}).HasConstraintName({quote(fkname)});")
config += ["    }", "}"]
context += ["}"]
(root / "src/Core/Hyper.Domain/Entities/Database/SqlServerEntities.cs").write_text("\n".join(entities), encoding="utf-8")
folder = root / "src/Core/Hyper.Infrastructure/Data/Repository/Hyper"
(folder / "HyperSqlServerModel.cs").write_text("\n".join(config), encoding="utf-8")
(folder / "HyperSqlServerContext.cs").write_text("\n".join(context), encoding="utf-8")
for oid, lines in integration_blocks.items():
    entity_type = integration_types[objects[oid]["name"]]
    for fkname, rows in foreign_keys[oid].items():
        rows.sort(key=lambda r: r["constraint_column_id"])
        principal = rows[0]["referenced_object_id"]
        target = integration_types[objects[principal]["name"]]
        fkprops = ", ".join(quote(name(col(oid, r["parent_column_id"])["name"])) for r in rows)
        lines.append(f"            entity.HasOne<{target}>().WithMany().HasForeignKey({fkprops}).OnDelete(DeleteBehavior.NoAction).HasConstraintName({quote(fkname)});")
    text = "\n".join(lines)
    for column in columns[oid]:
        text = text.replace(f"e.{name(column['name'])})", f"e.{column['name']})")
        text = text.replace(quote(name(column["name"])), quote(column["name"]))
    # Enabled/active defaults are true. false must be sent, not treated as an unset CLR default.
    for column in columns[oid]:
        if column["sql_type"] == "bit" and column["default_sql"] in ("((1))", "(1)"):
            text += f"\n            entity.Property(e => e.{column['name']}).HasSentinel(true);"
    output = ["// <auto-generated />", "using Hyper.Domain.Entities.Integrations;", "using Microsoft.EntityFrameworkCore;",
              "using Microsoft.EntityFrameworkCore.Metadata.Builders;", "namespace Hyper.Infrastructure.Data.Configurations;", "",
              f"public sealed class {entity_type}Configuration : IEntityTypeConfiguration<{entity_type}>", "{",
              f"    public void Configure(EntityTypeBuilder<{entity_type}> entity)", "    {", text, "    }", "}"]
    (root / f"src/Core/Hyper.Infrastructure/Data/Configurations/{entity_type}Configuration.cs").write_text("\n".join(output), encoding="utf-8")
print(f"Generated {len(objects)} records and {sum(map(len, columns.values()))} column mappings.")
for warning in warnings:
    print(warning)
