import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
admin=ROOT/'src/AdminPanel/Hyper.AdminPanel.Domain'
catalog=json.loads((ROOT/'docs/schema/sql-ui-catalog.json').read_text('utf-8'))
def quote(v):return json.dumps(v,ensure_ascii=False)
# Register only database-owned classes, never scan the copied assembly.
p=admin/'Domain/Hyper/HyperNamespace.cs';s=p.read_text('utf-8-sig')
s=s.replace('DefineEntities<IEntity>(typeof(SqlServerEntity).Assembly);','\n        '.join('DefineEntity<'+r['class']+'>();' for r in catalog))
p.write_text(s,'utf-8')
# Physical mapping and PK shape for inherited fields live in metadata refinement.
# Generated SQL mirror fields retain original CLR contracts.
sensitive=re.compile(r'password|^pwd$|salt|credentials|payloadjson|bytes|token|seed|text2',re.I)
code=['// <auto-generated by tools/Metadata/generate_sql_ui.py />','#nullable enable', 'using Hyper.Domain.Entities.Database;','using Neo.Bpms.Domain.Features.MetaDefinitions.Reports;','using Neo.Bpms.Domain.Models.Cmmn.UI.Reports;','using Neo.Bpms.Domain.Models.Cmmn.Fields;','namespace Hyper.AdminPanel.Domain.UiDefinitions.Database;','']
for r in catalog:
 c=r['class']; readonly=not r['table'].startswith('TBL_') or not r['keys']
 safe=[f for f in r['fields'] if not sensitive.search(f['property'])]
 cols=safe[:9]
 code += [f'public sealed class {c}UiDefinitions : CRUDDefinition<{c}>', '{','    public override List<string>? Roles => [HyperRoles.Admin];', '    protected override void RefineEntity()', '    {','        Entity.DontSync = true;', '        Entity.Schema = "dbo";',f'        Entity.DbTableNameMap = {quote(r["table"])};', '        Entity.AutoCalcs?.Calculations.Clear();','        foreach (var field in Entity.entityFields.Values)', '            field.Flags &= ~EntityFieldFlags.IncludeInPKV;']
 for f in r['fields']:
  prop=f['property']
  code += [f'        if (Entity.GetField(nameof({c}.{prop})) is {{ }} field{prop})', '        {',f'            field{prop}.DbFieldName = {quote(f["column"])};',f'            field{prop}.Name = {quote(f["title"])};']
  if prop in r['keys']:code+=[f'            field{prop}.Flags |= EntityFieldFlags.IncludeInPKV;']
  code += ['        }']
  if f['identity']:
   code += [f'        Entity.AutoCalcs ??= new(); Entity.AutoCalcs.AddAutoCalc(new Neo.Bpms.Domain.Models.Cmmn.AutoCalc {{ FieldId = nameof({c}.{prop}), GenerationType = Neo.Bpms.Domain.Models.Cmmn.AutoCalc.eGenerationType.DBInsert, Formula = Neo.Bpms.Domain.Expressions.Parsers.Parser.ParseTree("AutoIncrement()") }});']
 # Sensitive physical columns must not become generic form/report data sources.
 for f in r['fields']:
  if sensitive.search(f['property']):code += [f'        Entity.entityFields.TryRemove(nameof({c}.{f["property"]}), out _);']
 code+=['    }']
 if readonly:code+=['    protected override void Forms() => DefineCRUDForms("RL");']
 code += ['    protected override void IndexFormViewModel() => AddColumns('+', '.join('nameof('+c+'.'+f['property']+')' for f in cols)+');','    protected override void CUDFormsViewModel() => AddFields('+', '.join('nameof('+c+'.'+f['property']+')' for f in safe if not f['identity'])+');','    public new class PublicReport : CRUDDefinition.PublicReport','    {','        public override List<string>? Roles => [HyperRoles.Admin];','        public class CountConfig : ChartConfigDefinition','        {','            public CountConfig() : base(ChartType.MetricBox) { }','            protected override List<string> Roles => [HyperRoles.Admin];',f'            protected override string Name => {quote("تعداد " + r["title"])};','            protected override void DefineGroupBy() => Count(null, "تعداد");','        }']
 for prop in ['Status','Provider','IsEnabled','Shopid']:
  if prop in [f['property'] for f in safe]:
   label=next(f['title'] for f in safe if f['property']==prop)
   code += [f'        public class By{prop}Config : ChartConfigDefinition', '        {',f'            public By{prop}Config() : base(ChartType.Bar) {{ }}','            protected override List<string> Roles => [HyperRoles.Admin];',f'            protected override string Name => {quote(r["title"]+" به تفکیک "+label)};',f'            protected override void DefineGroupBy() {{ GroupBy(nameof({c}.{prop}), {quote(label)}); Count(null, "تعداد"); }}','        }']
 code+=['    }','}','']
out=admin/'UiDefinitions/Database';out.mkdir(exist_ok=True)
(out/'SqlEntityUiDefinitions.cs').write_text('\n'.join(code)+'\n','utf-8')
# Categorized menu and corresponding report for every concrete SQL mirror, including read-only views.
menu=['using Hyper.AdminPanel.Domain.UiDefinitions.HomePage;','using Hyper.Domain.Entities.Database;','namespace Hyper.AdminPanel.Domain.Domain;','public partial class HyperMenuDefinitions : MenuDefinition','{','    private void AddMenu_Hyper()','    {','        AddMenu<HomePageEntity, HomePageEntityUiDefinitions.HomePageDashboard>("داشبورد هایپریک", "home-dashboard");','        AddMenu("مغازه‌دار و اتصال", "building-organization", "MerchantSimulation", "Index");','        AddMenu("عملیات یکسان‌سازی", "activity-monitor", "MerchantSimulation", "Dashboard");']
groups={}
for r in catalog:groups.setdefault(r['category'],[]).append(r)
for i,(cat,rows) in enumerate(groups.items()):
 menu += [f'        AddMenu({quote(cat or "سایر")}, "database", "HyperCategory{i}", "");','        StartSubMenus();']
 for r in rows:menu += [f'        AddMenu<{r["class"]}>({quote(r["title"])}, "table");']
 menu += [f'        AddMenu("گزارش‌ها", "chart-bar", "HyperReports{i}", "");','        StartSubMenus();']
 for r in rows:menu += [f'        AddReport<{r["class"]}>({quote("گزارش "+r["title"])}, "chart-bar");']
 menu += ['        EndSubMenus();','        EndSubMenus();']
menu+=['    }','}']
(admin/'Menu/Menu_Hyper.cs').write_text('\n'.join(menu)+'\n','utf-8')
# Real metadata dashboards matching Club's nested dashboard config + widget convention.
sets=[('BusinessDashboard','مغازه و حسابداری',True,[('SqlTblShop','مغازه‌ها','CountConfig'),('SqlTblProduct','کالاها','CountConfig'),('SqlTblPerson','طرف حساب‌ها','CountConfig'),('SqlTblWarehouse','انبارها','CountConfig'),('SqlTblSaleorder','فاکتورهای فروش','CountConfig'),('SqlTblPurchaseorder','فاکتورهای خرید','CountConfig'),('SqlTblProduct','کالا به تفکیک مغازه','ByShopidConfig'),('SqlTblSaleorder','فروش به تفکیک مغازه','ByShopidConfig')]),('SynchronizationDashboard','یکسان‌سازی مغازه و غرفه',False,[('SqlExternalintegrationconnections','اتصال‌ها','CountConfig'),('SqlExternalproductmappings','نگاشت کالا','CountConfig'),('SqlIntegrationoutbox','پیام‌های خروجی','CountConfig'),('SqlIntegrationwebhookinbox','رویدادهای ورودی','CountConfig'),('SqlIntegrationsyncruns','وضعیت اجراها','ByStatusConfig'),('SqlIntegrationoutbox','وضعیت صف خروجی','ByStatusConfig'),('SqlIntegrationwebhookinbox','وضعیت صندوق ورودی','ByStatusConfig'),('SqlExternalintegrationconnections','اتصال به تفکیک پلتفرم','ByProviderConfig')])]
home=['using Hyper.Domain.Entities.Database;','using Hyper.AdminPanel.Domain.UiDefinitions.Database;','namespace Hyper.AdminPanel.Domain.UiDefinitions.HomePage;','public sealed class HomePageEntityUiDefinitions : CRUDDefinition<HomePageEntity>','{','    public override List<string>? Roles => [HyperRoles.Admin];','    public sealed class HomePageDashboard : DashboardDefinition','    {','        public override List<string>? Roles => [HyperRoles.Admin];','        protected override Form Identify() => DefineDashboard("داشبورد هایپریک و یکسان‌سازی");','        protected override void DataSources()','        {']
for c in dict.fromkeys(w[0] for x in sets for w in x[3]):home += [f'            AddReport<{c}>();']
home+=['        }']
for config,title,default,widgets in sets:
 home += [f'        public class {config} : DashboardConfigDefinition','        {',f'            protected override string Title => {quote(title)};','            protected override List<string> Roles => [HyperRoles.Admin];',f'            protected override bool IsDefault => {str(default).lower()};']
 for i,(c,t,reportconfig) in enumerate(widgets):
  home += [f'            public class Widget{i+1} : DashboardDivWidgetDefinition<{c}, {c}UiDefinitions.PublicReport, {c}UiDefinitions.PublicReport.{reportconfig}>','            {',f'                public override string Title => {quote(t)};',f'                public override int Width => {3 if i<4 else 6};',f'                protected override int? HeightInPixels => {160 if i<4 else 300};','                protected override int? CacheTimeMinutes => 1;','            }']
 home += ['        }']
home+=['    }','}']
(admin/'UiDefinitions/HomePage/HomePageEntityUiDefinitions.cs').write_text('\n'.join(home)+'\n','utf-8')
p=admin/'Hyper.AdminPanel.Domain.csproj'; s=p.read_text('utf-8-sig');s=s.replace('<Compile Include="UiDefinitions\\HomePage\\HomePageEntityUiDefinitions.cs" />','<Compile Include="UiDefinitions\\HomePage\\HomePageEntityUiDefinitions.cs" />\n    <Compile Include="UiDefinitions\\Database\\**\\*.cs" />');s=re.sub(r'(    <Compile Include="UiDefinitions\\Database\\\*\*\\\*\.cs" />\n)(?:\1)+',r'\1',s);p.write_text(s,'utf-8')
print('Generated',len(catalog),'Neo definitions, categorized menus/reports and 16 dashboard widgets.')
