// <auto-generated />
#nullable enable
namespace Hyper.Domain.Entities.Database;

public sealed class SqlActGeBytearray : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string? Name { get; set; }
    public string? DeploymentId { get; set; }
    public byte[]? Bytes { get; set; }
    public byte? Generated { get; set; }
    public string? TenantId { get; set; }
    public int? Type { get; set; }
    public DateTime? CreateTime { get; set; }
    public string? RootProcInstId { get; set; }
    public DateTime? RemovalTime { get; set; }
}

public sealed class SqlActGeProperty : SqlServerEntity
{
    public string Name { get; set; } = null!;
    public string? Value { get; set; }
    public int? Rev { get; set; }
}

public sealed class SqlActGeSchemaLog : SqlServerEntity<string>
{
    public DateTime? Timestamp { get; set; }
    public string? Version { get; set; }
}

public sealed class SqlActHiActinst : SqlServerEntity<string>
{
    public string? ParentActInstId { get; set; }
    public string? ProcDefKey { get; set; }
    public string ProcDefId { get; set; } = null!;
    public string? RootProcInstId { get; set; }
    public string ProcInstId { get; set; } = null!;
    public string ExecutionId { get; set; } = null!;
    public string ActId { get; set; } = null!;
    public string? TaskId { get; set; }
    public string? CallProcInstId { get; set; }
    public string? CallCaseInstId { get; set; }
    public string? ActName { get; set; }
    public string ActType { get; set; } = null!;
    public string? Assignee { get; set; }
    public DateTime StartTime { get; set; }
    public DateTime? EndTime { get; set; }
    public decimal? Duration { get; set; }
    public byte? ActInstState { get; set; }
    public decimal? SequenceCounter { get; set; }
    public string? TenantId { get; set; }
    public DateTime? RemovalTime { get; set; }
}

public sealed class SqlActHiAttachment : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string? UserId { get; set; }
    public string? Name { get; set; }
    public string? Description { get; set; }
    public string? Type { get; set; }
    public string? TaskId { get; set; }
    public string? RootProcInstId { get; set; }
    public string? ProcInstId { get; set; }
    public string? Url { get; set; }
    public string? ContentId { get; set; }
    public string? TenantId { get; set; }
    public DateTime? CreateTime { get; set; }
    public DateTime? RemovalTime { get; set; }
}

public sealed class SqlActHiBatch : SqlServerEntity<string>
{
    public string? Type { get; set; }
    public int? TotalJobs { get; set; }
    public int? JobsPerSeed { get; set; }
    public int? InvocationsPerJob { get; set; }
    public string? SeedJobDefId { get; set; }
    public string? MonitorJobDefId { get; set; }
    public string? BatchJobDefId { get; set; }
    public string? TenantId { get; set; }
    public string? CreateUserId { get; set; }
    public DateTime StartTime { get; set; }
    public DateTime? EndTime { get; set; }
    public DateTime? RemovalTime { get; set; }
}

public sealed class SqlActHiCaseactinst : SqlServerEntity<string>
{
    public string? ParentActInstId { get; set; }
    public string CaseDefId { get; set; } = null!;
    public string CaseInstId { get; set; } = null!;
    public string CaseActId { get; set; } = null!;
    public string? TaskId { get; set; }
    public string? CallProcInstId { get; set; }
    public string? CallCaseInstId { get; set; }
    public string? CaseActName { get; set; }
    public string? CaseActType { get; set; }
    public DateTime CreateTime { get; set; }
    public DateTime? EndTime { get; set; }
    public decimal? Duration { get; set; }
    public byte? State { get; set; }
    public byte? Required { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlActHiCaseinst : SqlServerEntity<string>
{
    public string CaseInstId { get; set; } = null!;
    public string? BusinessKey { get; set; }
    public string CaseDefId { get; set; } = null!;
    public DateTime CreateTime { get; set; }
    public DateTime? CloseTime { get; set; }
    public decimal? Duration { get; set; }
    public byte? State { get; set; }
    public string? CreateUserId { get; set; }
    public string? SuperCaseInstanceId { get; set; }
    public string? SuperProcessInstanceId { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlActHiComment : SqlServerEntity<string>
{
    public string? Type { get; set; }
    public DateTime Time { get; set; }
    public string? UserId { get; set; }
    public string? TaskId { get; set; }
    public string? RootProcInstId { get; set; }
    public string? ProcInstId { get; set; }
    public string? Action { get; set; }
    public string? Message { get; set; }
    public byte[]? FullMsg { get; set; }
    public string? TenantId { get; set; }
    public DateTime? RemovalTime { get; set; }
    public int Rev { get; set; }
}

public sealed class SqlActHiDecIn : SqlServerEntity<string>
{
    public string DecInstId { get; set; } = null!;
    public string? ClauseId { get; set; }
    public string? ClauseName { get; set; }
    public string? VarType { get; set; }
    public string? BytearrayId { get; set; }
    public double? Double { get; set; }
    public decimal? Long { get; set; }
    public string? Text { get; set; }
    public string? Text2 { get; set; }
    public string? TenantId { get; set; }
    public DateTime? CreateTime { get; set; }
    public string? RootProcInstId { get; set; }
    public DateTime? RemovalTime { get; set; }
}

public sealed class SqlActHiDecOut : SqlServerEntity<string>
{
    public string DecInstId { get; set; } = null!;
    public string? ClauseId { get; set; }
    public string? ClauseName { get; set; }
    public string? RuleId { get; set; }
    public int? RuleOrder { get; set; }
    public string? VarName { get; set; }
    public string? VarType { get; set; }
    public string? BytearrayId { get; set; }
    public double? Double { get; set; }
    public decimal? Long { get; set; }
    public string? Text { get; set; }
    public string? Text2 { get; set; }
    public string? TenantId { get; set; }
    public DateTime? CreateTime { get; set; }
    public string? RootProcInstId { get; set; }
    public DateTime? RemovalTime { get; set; }
}

public sealed class SqlActHiDecinst : SqlServerEntity<string>
{
    public string DecDefId { get; set; } = null!;
    public string DecDefKey { get; set; } = null!;
    public string? DecDefName { get; set; }
    public string? ProcDefKey { get; set; }
    public string? ProcDefId { get; set; }
    public string? ProcInstId { get; set; }
    public string? CaseDefKey { get; set; }
    public string? CaseDefId { get; set; }
    public string? CaseInstId { get; set; }
    public string? ActInstId { get; set; }
    public string? ActId { get; set; }
    public DateTime EvalTime { get; set; }
    public DateTime? RemovalTime { get; set; }
    public double? CollectValue { get; set; }
    public string? UserId { get; set; }
    public string? RootDecInstId { get; set; }
    public string? RootProcInstId { get; set; }
    public string? DecReqId { get; set; }
    public string? DecReqKey { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlActHiDetail : SqlServerEntity<string>
{
    public string Type { get; set; } = null!;
    public string? ProcDefKey { get; set; }
    public string? ProcDefId { get; set; }
    public string? RootProcInstId { get; set; }
    public string? ProcInstId { get; set; }
    public string? ExecutionId { get; set; }
    public string? CaseDefKey { get; set; }
    public string? CaseDefId { get; set; }
    public string? CaseInstId { get; set; }
    public string? CaseExecutionId { get; set; }
    public string? TaskId { get; set; }
    public string? ActInstId { get; set; }
    public string? VarInstId { get; set; }
    public string Name { get; set; } = null!;
    public string? VarType { get; set; }
    public int? Rev { get; set; }
    public DateTime Time { get; set; }
    public string? BytearrayId { get; set; }
    public double? Double { get; set; }
    public decimal? Long { get; set; }
    public string? Text { get; set; }
    public string? Text2 { get; set; }
    public decimal? SequenceCounter { get; set; }
    public string? TenantId { get; set; }
    public string? OperationId { get; set; }
    public DateTime? RemovalTime { get; set; }
    public bool? Initial { get; set; }
}

public sealed class SqlActHiExtTaskLog : SqlServerEntity<string>
{
    public DateTime Timestamp { get; set; }
    public string ExtTaskId { get; set; } = null!;
    public int? Retries { get; set; }
    public string? TopicName { get; set; }
    public string? WorkerId { get; set; }
    public decimal Priority { get; set; }
    public string? ErrorMsg { get; set; }
    public string? ErrorDetailsId { get; set; }
    public string? ActId { get; set; }
    public string? ActInstId { get; set; }
    public string? ExecutionId { get; set; }
    public string? RootProcInstId { get; set; }
    public string? ProcInstId { get; set; }
    public string? ProcDefId { get; set; }
    public string? ProcDefKey { get; set; }
    public string? TenantId { get; set; }
    public int? State { get; set; }
    public DateTime? RemovalTime { get; set; }
}

public sealed class SqlActHiIdentitylink : SqlServerEntity<string>
{
    public DateTime Timestamp { get; set; }
    public string? Type { get; set; }
    public string? UserId { get; set; }
    public string? GroupId { get; set; }
    public string? TaskId { get; set; }
    public string? RootProcInstId { get; set; }
    public string? ProcDefId { get; set; }
    public string? OperationType { get; set; }
    public string? AssignerId { get; set; }
    public string? ProcDefKey { get; set; }
    public string? TenantId { get; set; }
    public DateTime? RemovalTime { get; set; }
}

public sealed class SqlActHiIncident : SqlServerEntity<string>
{
    public string? ProcDefKey { get; set; }
    public string? ProcDefId { get; set; }
    public string? RootProcInstId { get; set; }
    public string? ProcInstId { get; set; }
    public string? ExecutionId { get; set; }
    public DateTime CreateTime { get; set; }
    public DateTime? EndTime { get; set; }
    public string? IncidentMsg { get; set; }
    public string IncidentType { get; set; } = null!;
    public string? ActivityId { get; set; }
    public string? FailedActivityId { get; set; }
    public string? CauseIncidentId { get; set; }
    public string? RootCauseIncidentId { get; set; }
    public string? Configuration { get; set; }
    public string? HistoryConfiguration { get; set; }
    public int? IncidentState { get; set; }
    public string? TenantId { get; set; }
    public string? JobDefId { get; set; }
    public string? Annotation { get; set; }
    public DateTime? RemovalTime { get; set; }
}

public sealed class SqlActHiJobLog : SqlServerEntity<string>
{
    public DateTime Timestamp { get; set; }
    public string JobId { get; set; } = null!;
    public DateTime? JobDuedate { get; set; }
    public int? JobRetries { get; set; }
    public decimal JobPriority { get; set; }
    public string? JobExceptionMsg { get; set; }
    public string? JobExceptionStackId { get; set; }
    public int? JobState { get; set; }
    public string? JobDefId { get; set; }
    public string? JobDefType { get; set; }
    public string? JobDefConfiguration { get; set; }
    public string? ActId { get; set; }
    public string? FailedActId { get; set; }
    public string? ExecutionId { get; set; }
    public string? RootProcInstId { get; set; }
    public string? ProcessInstanceId { get; set; }
    public string? ProcessDefId { get; set; }
    public string? ProcessDefKey { get; set; }
    public string? DeploymentId { get; set; }
    public decimal? SequenceCounter { get; set; }
    public string? TenantId { get; set; }
    public string? Hostname { get; set; }
    public DateTime? RemovalTime { get; set; }
    public string? BatchId { get; set; }
}

public sealed class SqlActHiOpLog : SqlServerEntity<string>
{
    public string? DeploymentId { get; set; }
    public string? ProcDefId { get; set; }
    public string? ProcDefKey { get; set; }
    public string? RootProcInstId { get; set; }
    public string? ProcInstId { get; set; }
    public string? ExecutionId { get; set; }
    public string? CaseDefId { get; set; }
    public string? CaseInstId { get; set; }
    public string? CaseExecutionId { get; set; }
    public string? TaskId { get; set; }
    public string? JobId { get; set; }
    public string? JobDefId { get; set; }
    public string? BatchId { get; set; }
    public string? UserId { get; set; }
    public DateTime Timestamp { get; set; }
    public string? OperationType { get; set; }
    public string? OperationId { get; set; }
    public string? EntityType { get; set; }
    public string? Property { get; set; }
    public string? OrgValue { get; set; }
    public string? NewValue { get; set; }
    public string? TenantId { get; set; }
    public DateTime? RemovalTime { get; set; }
    public string? Category { get; set; }
    public string? ExternalTaskId { get; set; }
    public string? Annotation { get; set; }
}

public sealed class SqlActHiProcinst : SqlServerEntity<string>
{
    public string ProcInstId { get; set; } = null!;
    public string? BusinessKey { get; set; }
    public string? ProcDefKey { get; set; }
    public string ProcDefId { get; set; } = null!;
    public DateTime StartTime { get; set; }
    public DateTime? EndTime { get; set; }
    public DateTime? RemovalTime { get; set; }
    public decimal? Duration { get; set; }
    public string? StartUserId { get; set; }
    public string? StartActId { get; set; }
    public string? EndActId { get; set; }
    public string? SuperProcessInstanceId { get; set; }
    public string? RootProcInstId { get; set; }
    public string? SuperCaseInstanceId { get; set; }
    public string? CaseInstId { get; set; }
    public string? DeleteReason { get; set; }
    public string? TenantId { get; set; }
    public string? State { get; set; }
    public string? RestartedProcInstId { get; set; }
}

public sealed class SqlActHiTaskinst : SqlServerEntity<string>
{
    public string? TaskDefKey { get; set; }
    public string? ProcDefKey { get; set; }
    public string? ProcDefId { get; set; }
    public string? RootProcInstId { get; set; }
    public string? ProcInstId { get; set; }
    public string? ExecutionId { get; set; }
    public string? CaseDefKey { get; set; }
    public string? CaseDefId { get; set; }
    public string? CaseInstId { get; set; }
    public string? CaseExecutionId { get; set; }
    public string? ActInstId { get; set; }
    public string? Name { get; set; }
    public string? ParentTaskId { get; set; }
    public string? Description { get; set; }
    public string? Owner { get; set; }
    public string? Assignee { get; set; }
    public DateTime StartTime { get; set; }
    public DateTime? EndTime { get; set; }
    public decimal? Duration { get; set; }
    public string? DeleteReason { get; set; }
    public int? Priority { get; set; }
    public DateTime? DueDate { get; set; }
    public DateTime? FollowUpDate { get; set; }
    public string? TenantId { get; set; }
    public DateTime? RemovalTime { get; set; }
    public string? TaskState { get; set; }
}

public sealed class SqlActHiVarinst : SqlServerEntity<string>
{
    public string? ProcDefKey { get; set; }
    public string? ProcDefId { get; set; }
    public string? RootProcInstId { get; set; }
    public string? ProcInstId { get; set; }
    public string? ExecutionId { get; set; }
    public string? CaseDefKey { get; set; }
    public string? CaseDefId { get; set; }
    public string? CaseInstId { get; set; }
    public string? CaseExecutionId { get; set; }
    public string? ActInstId { get; set; }
    public string? TaskId { get; set; }
    public string Name { get; set; } = null!;
    public string? VarType { get; set; }
    public DateTime? CreateTime { get; set; }
    public int? Rev { get; set; }
    public string? BytearrayId { get; set; }
    public double? Double { get; set; }
    public decimal? Long { get; set; }
    public string? Text { get; set; }
    public string? Text2 { get; set; }
    public string? TenantId { get; set; }
    public string? State { get; set; }
    public DateTime? RemovalTime { get; set; }
}

public sealed class SqlActIdGroup : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string? Name { get; set; }
    public string? Type { get; set; }
}

public sealed class SqlActIdInfo : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string? UserId { get; set; }
    public string? Type { get; set; }
    public string? Key { get; set; }
    public string? Value { get; set; }
    public byte[]? Password { get; set; }
    public string? ParentId { get; set; }
}

public sealed class SqlActIdMembership : SqlServerEntity
{
    public string UserId { get; set; } = null!;
    public string GroupId { get; set; } = null!;
    public string? TenantId { get; set; }
    public string? Hash { get; set; }
    public DateTime? RemovalTime { get; set; }
}

public sealed class SqlActIdRememberMe : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string Selector { get; set; } = null!;
    public string Validator { get; set; } = null!;
    public string UserId { get; set; } = null!;
    public DateTime LastUsed { get; set; }
}

public sealed class SqlActIdTenant : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string? Name { get; set; }
    public string? ParentId { get; set; }
}

public sealed class SqlActIdTenantMember : SqlServerEntity<string>
{
    public string TenantId { get; set; } = null!;
    public string? UserId { get; set; }
    public string? GroupId { get; set; }
    public DateTime? RemovalTime { get; set; }
}

public sealed class SqlActIdUser : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string? First { get; set; }
    public string? Last { get; set; }
    public string? Email { get; set; }
    public string? Pwd { get; set; }
    public string? Salt { get; set; }
    public DateTime? LockExpTime { get; set; }
    public int? Attempts { get; set; }
    public string? PictureId { get; set; }
    public string? Mobile { get; set; }
    public DateTime CreateTime { get; set; }
    public DateTime? UpdateTime { get; set; }
    public bool Block { get; set; }
    public string Fullname { get; set; } = null!;
    public string? Hash { get; set; }
}

public sealed class SqlActReAssociation : SqlServerEntity
{
    public string Id { get; set; } = null!;
    public string Name { get; set; } = null!;
    public int Rev { get; set; }
    public string Type { get; set; } = null!;
    public string TableId { get; set; } = null!;
    public string? IncomingName { get; set; }
    public string? OutcomingName { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlActReCamformdef : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string Key { get; set; } = null!;
    public int Version { get; set; }
    public string? DeploymentId { get; set; }
    public string? ResourceName { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlActReCaseDef : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string? Category { get; set; }
    public string? Name { get; set; }
    public string Key { get; set; } = null!;
    public int Version { get; set; }
    public string? DeploymentId { get; set; }
    public string? ResourceName { get; set; }
    public string? DgrmResourceName { get; set; }
    public string? TenantId { get; set; }
    public int? HistoryTtl { get; set; }
}

public sealed class SqlActReColumn : SqlServerEntity
{
    public string Id { get; set; } = null!;
    public string? OldId { get; set; }
    public int Rev { get; set; }
    public int? Index { get; set; }
    public string Name { get; set; } = null!;
    public bool Nullable { get; set; }
    public string Type { get; set; } = null!;
    public string Key { get; set; } = null!;
    public bool? Normalize { get; set; }
    public string? Details { get; set; }
    public string TableId { get; set; } = null!;
    public bool Default { get; set; }
    public string? TenantId { get; set; }
    public int Kind { get; set; }
    public bool? EscapeHtml { get; set; }
}

public sealed class SqlActReConstraint : SqlServerEntity<string>
{
    public string Name { get; set; } = null!;
    public int Rev { get; set; }
    public string Type { get; set; } = null!;
    public string TableId { get; set; } = null!;
    public string ColumnId { get; set; } = null!;
    public string? ParentTableId { get; set; }
    public string? ParentColumnId { get; set; }
    public string? TenantId { get; set; }
    public string? UpdateRule { get; set; }
    public string? DeleteRule { get; set; }
    public string? SqlScript { get; set; }
    public string? ErrorMessage { get; set; }
}

public sealed class SqlActReDashboard : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string Name { get; set; } = null!;
    public string? Category { get; set; }
    public string? Definition { get; set; }
    public bool Default { get; set; }
    public DateTime CreateTime { get; set; }
    public DateTime? UpdateTime { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlActReDataForm : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string Name { get; set; } = null!;
    public string? Category { get; set; }
    public string TableId { get; set; } = null!;
    public string? TenantId { get; set; }
    public string? CustomHints { get; set; }
    public bool Sync { get; set; }
}

public sealed class SqlActReDataFormColumn : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string? Name { get; set; }
    public int Type { get; set; }
    public double Order { get; set; }
    public bool? Visible { get; set; }
    public bool? Summable { get; set; }
    public bool? Filterable { get; set; }
    public bool? Suggestable { get; set; }
    public string? Category { get; set; }
    public int? ShowType { get; set; }
    public int? ActionType { get; set; }
    public string DataFormId { get; set; } = null!;
    public string? RefTableId { get; set; }
    public string? RefColumnId { get; set; }
    public string? RefFormId { get; set; }
    public string? RefFormRelations { get; set; }
    public string? RefDataFormId { get; set; }
    public string? RefAssociationTableId { get; set; }
    public string? RefAssociationId { get; set; }
    public string? ChainAssociations { get; set; }
    public string? TenantId { get; set; }
    public string? DataFormat { get; set; }
    public string? SqlScript { get; set; }
    public string? SqlResultType { get; set; }
    public string? SuggestDetails { get; set; }
    public string? OperationDetails { get; set; }
    public bool? OutFullData { get; set; }
    public string? ReadonlyRelations { get; set; }
    public bool? Sortable { get; set; }
    public string? Icon { get; set; }
    public bool? Exportable { get; set; }
    public string? Tags { get; set; }
}

public sealed class SqlActReDataFormFilter : SqlServerEntity<string>
{
    public string? Value { get; set; }
    public string DataFormId { get; set; } = null!;
    public string? TenantId { get; set; }
}

public sealed class SqlActReDataFormHeader : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string? Name { get; set; }
    public int Type { get; set; }
    public double Order { get; set; }
    public int? ActionType { get; set; }
    public string DataFormId { get; set; } = null!;
    public string? AssigneeVar { get; set; }
    public string? RefFormId { get; set; }
    public string? ProcessKey { get; set; }
    public string? ProcessKeyName { get; set; }
    public string? ProcessTenantId { get; set; }
    public int? ProcessBindingType { get; set; }
    public string? ProcessTag { get; set; }
    public string? TenantId { get; set; }
    public bool? InlineEdit { get; set; }
    public bool? ProcessNeedRow { get; set; }
    public int? ExportType { get; set; }
    public bool? OutFullData { get; set; }
    public string? ReadonlyRelations { get; set; }
    public string? RefFormRelations { get; set; }
    public string? ExportDetail { get; set; }
    public int? ExportLimit { get; set; }
}

public sealed class SqlActReDataFormSort : SqlServerEntity<string>
{
    public string? Value { get; set; }
    public string DataFormId { get; set; } = null!;
    public string? TenantId { get; set; }
}

public sealed class SqlActReDataReport : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string Name { get; set; } = null!;
    public string? Category { get; set; }
    public string FormId { get; set; } = null!;
    public string? TenantId { get; set; }
    public string? CustomHints { get; set; }
}

public sealed class SqlActReDataReportColumn : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string? Name { get; set; }
    public int Type { get; set; }
    public double Order { get; set; }
    public string DataReportId { get; set; } = null!;
    public string? RefDataFormId { get; set; }
    public string? RefDataColumnId { get; set; }
    public string? Aggregation { get; set; }
    public string? DataFormat { get; set; }
    public string? TenantId { get; set; }
    public string? RefDataFilterColumnId { get; set; }
    public bool? Summable { get; set; }
}

public sealed class SqlActReDataReportFilter : SqlServerEntity<string>
{
    public string? Value { get; set; }
    public string DataReportId { get; set; } = null!;
    public string? TenantId { get; set; }
}

public sealed class SqlActReDataReportHeader : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string? Name { get; set; }
    public int Type { get; set; }
    public double Order { get; set; }
    public int? ExportType { get; set; }
    public string DataReportId { get; set; } = null!;
    public string? TenantId { get; set; }
    public string? ExportDetail { get; set; }
    public int? ExportLimit { get; set; }
}

public sealed class SqlActReDataReportSort : SqlServerEntity<string>
{
    public string? Value { get; set; }
    public string DataReportId { get; set; } = null!;
    public string? TenantId { get; set; }
}

public sealed class SqlActReDecisionDef : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string? Category { get; set; }
    public string? Name { get; set; }
    public string Key { get; set; } = null!;
    public int Version { get; set; }
    public string? DeploymentId { get; set; }
    public string? ResourceName { get; set; }
    public string? DgrmResourceName { get; set; }
    public string? DecReqId { get; set; }
    public string? DecReqKey { get; set; }
    public string? TenantId { get; set; }
    public int? HistoryTtl { get; set; }
    public string? VersionTag { get; set; }
}

public sealed class SqlActReDecisionReqDef : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string? Category { get; set; }
    public string? Name { get; set; }
    public string Key { get; set; } = null!;
    public int Version { get; set; }
    public string? DeploymentId { get; set; }
    public string? ResourceName { get; set; }
    public string? DgrmResourceName { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlActReDeployment : SqlServerEntity<string>
{
    public string? Name { get; set; }
    public DateTime? DeployTime { get; set; }
    public string? Source { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlActReForm : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string Name { get; set; } = null!;
    public string? Category { get; set; }
    public string? Definition { get; set; }
    public DateTime CreateTime { get; set; }
    public DateTime? UpdateTime { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlActReLink : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string Name { get; set; } = null!;
    public string? Description { get; set; }
    public string Url { get; set; } = null!;
    public double Order { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlActReMenu : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string Name { get; set; } = null!;
    public int Type { get; set; }
    public string? Logo { get; set; }
    public string? Detail { get; set; }
    public double Order { get; set; }
    public string? ParentId { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlActReModel : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string Name { get; set; } = null!;
    public string? Category { get; set; }
    public string? Definition { get; set; }
    public int Type { get; set; }
    public DateTime CreateTime { get; set; }
    public DateTime? UpdateTime { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlActReNotification : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string? Sender { get; set; }
    public string? GroupId { get; set; }
    public string? UserId { get; set; }
    public string Message { get; set; } = null!;
    public string? Type { get; set; }
    public string? Target { get; set; }
    public bool? Enable { get; set; }
    public DateTime? StartTime { get; set; }
    public DateTime? EndTime { get; set; }
    public DateTime ChangeTime { get; set; }
    public string? TenantId { get; set; }
    public string? Details { get; set; }
}

public sealed class SqlActReNotificationStatus : SqlServerEntity
{
    public string NotificationId { get; set; } = null!;
    public string UserId { get; set; } = null!;
    public bool? Read { get; set; }
    public bool? Deleted { get; set; }
}

public sealed class SqlActReProcdef : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string? Category { get; set; }
    public string? Name { get; set; }
    public string Key { get; set; } = null!;
    public int Version { get; set; }
    public string? DeploymentId { get; set; }
    public string? ResourceName { get; set; }
    public string? DgrmResourceName { get; set; }
    public byte? HasStartFormKey { get; set; }
    public byte? SuspensionState { get; set; }
    public string? TenantId { get; set; }
    public string? VersionTag { get; set; }
    public int? HistoryTtl { get; set; }
    public bool Startable { get; set; }
}

public sealed class SqlActReQuery : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string Name { get; set; } = null!;
    public string? Category { get; set; }
    public int Type { get; set; }
    public string? Definition { get; set; }
    public DateTime CreateTime { get; set; }
    public DateTime? UpdateTime { get; set; }
    public string? TenantId { get; set; }
    public int? ExportType { get; set; }
    public string? ExportDetail { get; set; }
    public int? ExportLimit { get; set; }
}

public sealed class SqlActReReport : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string Name { get; set; } = null!;
    public string? Folder { get; set; }
    public string? Definition { get; set; }
    public DateTime CreateTime { get; set; }
    public DateTime? UpdateTime { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlActReTable : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string Name { get; set; } = null!;
    public string? Category { get; set; }
    public bool Sync { get; set; }
    public bool Default { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlActReTopic : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string Name { get; set; } = null!;
    public int Type { get; set; }
    public string? PackagesClass { get; set; }
    public bool Default { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlActRuAuthorization : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public int Type { get; set; }
    public string? GroupId { get; set; }
    public string? UserId { get; set; }
    public int ResourceType { get; set; }
    public string? ResourceId { get; set; }
    public int? Perms { get; set; }
    public DateTime? RemovalTime { get; set; }
    public string? RootProcInstId { get; set; }
    public string? Hash { get; set; }
}

public sealed class SqlActRuBatch : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string? Type { get; set; }
    public int? TotalJobs { get; set; }
    public int? JobsCreated { get; set; }
    public int? JobsPerSeed { get; set; }
    public int? InvocationsPerJob { get; set; }
    public string? SeedJobDefId { get; set; }
    public string? BatchJobDefId { get; set; }
    public string? MonitorJobDefId { get; set; }
    public byte? SuspensionState { get; set; }
    public string? Configuration { get; set; }
    public string? TenantId { get; set; }
    public string? CreateUserId { get; set; }
    public DateTime? StartTime { get; set; }
}

public sealed class SqlActRuCaseExecution : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string? CaseInstId { get; set; }
    public string? SuperCaseExec { get; set; }
    public string? SuperExec { get; set; }
    public string? BusinessKey { get; set; }
    public string? ParentId { get; set; }
    public string? CaseDefId { get; set; }
    public string? ActId { get; set; }
    public int? PrevState { get; set; }
    public int? CurrentState { get; set; }
    public byte? Required { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlActRuCaseSentryPart : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string? CaseInstId { get; set; }
    public string? CaseExecId { get; set; }
    public string? SentryId { get; set; }
    public string? Type { get; set; }
    public string? SourceCaseExecId { get; set; }
    public string? StandardEvent { get; set; }
    public string? Source { get; set; }
    public string? VariableEvent { get; set; }
    public string? VariableName { get; set; }
    public byte? Satisfied { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlActRuChangeQueue : SqlServerEntity<string>
{
    public DateTime Time { get; set; }
    public string Type { get; set; } = null!;
    public string Action { get; set; } = null!;
    public string TargetId { get; set; } = null!;
}

public sealed class SqlActRuEventSubscr : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string EventType { get; set; } = null!;
    public string? EventName { get; set; }
    public string? ExecutionId { get; set; }
    public string? ProcInstId { get; set; }
    public string? ActivityId { get; set; }
    public string? Configuration { get; set; }
    public DateTime Created { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlActRuExecution : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string? RootProcInstId { get; set; }
    public string? ProcInstId { get; set; }
    public string? BusinessKey { get; set; }
    public string? ParentId { get; set; }
    public string? ProcDefId { get; set; }
    public string? SuperExec { get; set; }
    public string? SuperCaseExec { get; set; }
    public string? CaseInstId { get; set; }
    public string? ActId { get; set; }
    public string? ActInstId { get; set; }
    public byte? IsActive { get; set; }
    public byte? IsConcurrent { get; set; }
    public byte? IsScope { get; set; }
    public byte? IsEventScope { get; set; }
    public byte? SuspensionState { get; set; }
    public int? CachedEntState { get; set; }
    public decimal? SequenceCounter { get; set; }
    public string? TenantId { get; set; }
    public string? ProcDefKey { get; set; }
}

public sealed class SqlActRuExtTask : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string? WorkerId { get; set; }
    public string? TopicName { get; set; }
    public int? Retries { get; set; }
    public string? ErrorMsg { get; set; }
    public string? ErrorDetailsId { get; set; }
    public DateTime? LockExpTime { get; set; }
    public byte? SuspensionState { get; set; }
    public string? ExecutionId { get; set; }
    public string? ProcInstId { get; set; }
    public string? ProcDefId { get; set; }
    public string? ProcDefKey { get; set; }
    public string? ActId { get; set; }
    public string? ActInstId { get; set; }
    public string? TenantId { get; set; }
    public decimal Priority { get; set; }
    public string? LastFailureLogId { get; set; }
    public DateTime? CreateTime { get; set; }
}

public sealed class SqlActRuFilter : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public string ResourceType { get; set; } = null!;
    public string Name { get; set; } = null!;
    public string? Owner { get; set; }
    public string Query { get; set; } = null!;
    public string? Properties { get; set; }
}

public sealed class SqlActRuIdentitylink : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string? GroupId { get; set; }
    public string? Type { get; set; }
    public string? UserId { get; set; }
    public string? TaskId { get; set; }
    public string? ProcDefId { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlActRuIncident : SqlServerEntity<string>
{
    public int Rev { get; set; }
    public DateTime IncidentTimestamp { get; set; }
    public string? IncidentMsg { get; set; }
    public string IncidentType { get; set; } = null!;
    public string? ExecutionId { get; set; }
    public string? ActivityId { get; set; }
    public string? FailedActivityId { get; set; }
    public string? ProcInstId { get; set; }
    public string? ProcDefId { get; set; }
    public string? CauseIncidentId { get; set; }
    public string? RootCauseIncidentId { get; set; }
    public string? Configuration { get; set; }
    public string? TenantId { get; set; }
    public string? JobDefId { get; set; }
    public string? Annotation { get; set; }
}

public sealed class SqlActRuJob : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string Type { get; set; } = null!;
    public DateTime? LockExpTime { get; set; }
    public string? LockOwner { get; set; }
    public bool? Exclusive { get; set; }
    public string? ExecutionId { get; set; }
    public string? ProcessInstanceId { get; set; }
    public string? ProcessDefId { get; set; }
    public string? ProcessDefKey { get; set; }
    public int? Retries { get; set; }
    public string? ExceptionStackId { get; set; }
    public string? ExceptionMsg { get; set; }
    public string? FailedActId { get; set; }
    public DateTime? Duedate { get; set; }
    public string? Repeat { get; set; }
    public decimal? RepeatOffset { get; set; }
    public string? HandlerType { get; set; }
    public string? HandlerCfg { get; set; }
    public string? DeploymentId { get; set; }
    public byte SuspensionState { get; set; }
    public decimal Priority { get; set; }
    public string? JobDefId { get; set; }
    public decimal? SequenceCounter { get; set; }
    public string? TenantId { get; set; }
    public DateTime? CreateTime { get; set; }
    public string? LastFailureLogId { get; set; }
    public string? RootProcInstId { get; set; }
    public string? Username { get; set; }
    public string? BatchId { get; set; }
}

public sealed class SqlActRuJobdef : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string? ProcDefId { get; set; }
    public string? ProcDefKey { get; set; }
    public string? ActId { get; set; }
    public string JobType { get; set; } = null!;
    public string? JobConfiguration { get; set; }
    public byte? SuspensionState { get; set; }
    public decimal? JobPriority { get; set; }
    public string? TenantId { get; set; }
    public string? DeploymentId { get; set; }
}

public sealed class SqlActRuMeterLog : SqlServerEntity<string>
{
    public string Name { get; set; } = null!;
    public string? Reporter { get; set; }
    public decimal? Value { get; set; }
    public DateTime? Timestamp { get; set; }
    public decimal? Milliseconds { get; set; }
}

public sealed class SqlActRuTask : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string? ExecutionId { get; set; }
    public string? ProcInstId { get; set; }
    public string? ProcDefId { get; set; }
    public string? CaseExecutionId { get; set; }
    public string? CaseInstId { get; set; }
    public string? CaseDefId { get; set; }
    public string? Name { get; set; }
    public string? ParentTaskId { get; set; }
    public string? Description { get; set; }
    public string? TaskDefKey { get; set; }
    public string? Owner { get; set; }
    public string? Assignee { get; set; }
    public string? Delegation { get; set; }
    public int? Priority { get; set; }
    public DateTime? CreateTime { get; set; }
    public DateTime? DueDate { get; set; }
    public DateTime? FollowUpDate { get; set; }
    public int? SuspensionState { get; set; }
    public string? TenantId { get; set; }
    public DateTime? LastUpdated { get; set; }
    public string? TaskState { get; set; }
}

public sealed class SqlActRuTaskMeterLog : SqlServerEntity<string>
{
    public decimal? AssigneeHash { get; set; }
    public DateTime? Timestamp { get; set; }
}

public sealed class SqlActRuVariable : SqlServerEntity<string>
{
    public int? Rev { get; set; }
    public string Type { get; set; } = null!;
    public string Name { get; set; } = null!;
    public string? ExecutionId { get; set; }
    public string? ProcInstId { get; set; }
    public string? ProcDefId { get; set; }
    public string? CaseExecutionId { get; set; }
    public string? CaseInstId { get; set; }
    public string? TaskId { get; set; }
    public string? BatchId { get; set; }
    public string? BytearrayId { get; set; }
    public double? Double { get; set; }
    public decimal? Long { get; set; }
    public string? Text { get; set; }
    public string? Text2 { get; set; }
    public string VarScope { get; set; } = null!;
    public decimal? SequenceCounter { get; set; }
    public byte? IsConcurrentLocal { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlExternalintegrationconnections : SqlServerEntity<long>
{
    public int Shopid { get; set; }
    public string Tenantid { get; set; } = null!;
    public byte Provider { get; set; }
    public string Displayname { get; set; } = null!;
    public string Accountidentifier { get; set; } = null!;
    public byte Credentialtype { get; set; }
    public string Credentialsjson { get; set; } = null!;
    public DateTime? Expiresatutc { get; set; }
    public bool Isenabled { get; set; }
    public DateTime Connectedatutc { get; set; }
    public DateTime? Lastsyncatutc { get; set; }
    public string? Lasterror { get; set; }
}

public sealed class SqlExternalordermappings : SqlServerEntity<long>
{
    public long Connectionid { get; set; }
    public int Shopid { get; set; }
    public long? Hypersaleorderid { get; set; }
    public string Externalorderid { get; set; } = null!;
    public string? Externalparcelid { get; set; }
    public byte Status { get; set; }
    public DateTime? Lastsyncatutc { get; set; }
}

public sealed class SqlExternalproductmappings : SqlServerEntity<long>
{
    public long Connectionid { get; set; }
    public int Shopid { get; set; }
    public int Hyperproductid { get; set; }
    public string Externalproductid { get; set; } = null!;
    public string? Externalsku { get; set; }
    public string? Externalvariantid { get; set; }
    public decimal? Lastexternalprice { get; set; }
    public decimal? Lastexternalinventory { get; set; }
    public DateTime? Lastsyncatutc { get; set; }
    public bool Isactive { get; set; }
}

public sealed class SqlIntegrationadminsimulations : SqlServerEntity<Guid>
{
    public string Adminuserid { get; set; } = null!;
    public int Shopid { get; set; }
    public string Merchantidentifier { get; set; } = null!;
    public string Tenantid { get; set; } = null!;
    public string Shopname { get; set; } = null!;
    public DateTime Createdatutc { get; set; }
    public DateTime Expiresatutc { get; set; }
    public DateTime? Endedatutc { get; set; }
}

public sealed class SqlIntegrationeventaudits : SqlServerEntity<long>
{
    public long? Connectionid { get; set; }
    public string Direction { get; set; } = null!;
    public string Eventtype { get; set; } = null!;
    public string Externaleventid { get; set; } = null!;
    public string Payloadhash { get; set; } = null!;
    public bool Signaturevalid { get; set; }
    public string? Correlationid { get; set; }
    public DateTime Receivedatutc { get; set; }
}

public sealed class SqlIntegrationmerchantaccess : SqlServerEntity<long>
{
    public string Issuer { get; set; } = null!;
    public string Subjectid { get; set; } = null!;
    public int Shopid { get; set; }
    public bool Isenabled { get; set; }
    public DateTime Createdatutc { get; set; }
    public string Createdby { get; set; } = null!;
    public DateTime? Expiresatutc { get; set; }
    public DateTime? Revokedatutc { get; set; }
}

public sealed class SqlIntegrationoutbox : SqlServerEntity<long>
{
    public long Connectionid { get; set; }
    public long Mappingid { get; set; }
    public long Sourceversion { get; set; }
    public string Operation { get; set; } = null!;
    public string Payloadjson { get; set; } = null!;
    public byte Status { get; set; }
    public int Attempts { get; set; }
    public DateTime Createdatutc { get; set; }
    public DateTime Nextattemptatutc { get; set; }
    public Guid? Leaseid { get; set; }
    public DateTime? Leaseexpiresatutc { get; set; }
    public DateTime? Completedatutc { get; set; }
    public string? Lasterror { get; set; }
}

public sealed class SqlIntegrationsyncruns : SqlServerEntity<long>
{
    public long Connectionid { get; set; }
    public DateTime Startedatutc { get; set; }
    public DateTime? Finishedatutc { get; set; }
    public byte Status { get; set; }
    public int Itemsread { get; set; }
    public int Itemswritten { get; set; }
    public int Itemsfailed { get; set; }
    public string? Error { get; set; }
}

public sealed class SqlIntegrationtokenrequests : SqlServerEntity<Guid>
{
    public Guid Simulationid { get; set; }
    public byte Provider { get; set; }
    public byte Credentialtype { get; set; }
    public byte Status { get; set; }
    public DateTime Requestedatutc { get; set; }
}

public sealed class SqlIntegrationwebhookinbox : SqlServerEntity<long>
{
    public long Connectionid { get; set; }
    public string Externaleventid { get; set; } = null!;
    public string Eventtype { get; set; } = null!;
    public string Payloadjson { get; set; } = null!;
    public DateTime Receivedatutc { get; set; }
    public DateTime? Processedatutc { get; set; }
    public byte Status { get; set; }
    public string? Error { get; set; }
}

public sealed class SqlInventoryreservationlogs : SqlServerEntity<long>
{
    public int Shopid { get; set; }
    public int Hyperproductid { get; set; }
    public string Reservationkey { get; set; } = null!;
    public decimal Quantity { get; set; }
    public byte Status { get; set; }
    public string Source { get; set; } = null!;
    public DateTime Createdatutc { get; set; }
    public DateTime? Releasedatutc { get; set; }
}

public sealed class SqlTblAccount : SqlServerEntity
{
    public int Accountid { get; set; }
    public int? Shopid { get; set; }
    public bool? Type { get; set; }
    public byte? Detailtype { get; set; }
    public bool? Nature { get; set; }
    public int? Parentid { get; set; }
    public string? Code { get; set; }
    public string Name { get; set; } = null!;
    public byte Level { get; set; }
    public int? Referenceid { get; set; }
    public bool Ispostable { get; set; }
    public short? Globalaccountkey { get; set; }
    public string? Description { get; set; }
    public int? Fiscalperiodid { get; set; }
    public byte? Reporttype { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblAccountingarticle : SqlServerEntity<long>
{
    public long Documentid { get; set; }
    public string? TenantId { get; set; }
    public int Shopid { get; set; }
    public long? Detailaccountid { get; set; }
    public string? Description { get; set; }
    public int Accountid { get; set; }
    public decimal Amount { get; set; }
    public string Currency { get; set; } = null!;
    public int? Checkid { get; set; }
    public decimal Exchangerate { get; set; }
    public bool Type { get; set; }
    public decimal Baseamount { get; set; }
}

public sealed class SqlTblAccountingdocument : SqlServerEntity<long>
{
    public string? Description { get; set; }
    public string? TenantId { get; set; }
    public int Shopid { get; set; }
    public int Fiscalperiodid { get; set; }
    public decimal Totalbaseamount { get; set; }
    public int? Referencenumber { get; set; }
    public byte Status { get; set; }
    public int? Number { get; set; }
    public DateOnly Date { get; set; }
    public byte Primarytype { get; set; }
    public byte Referencetype { get; set; }
    public long? Referenceid { get; set; }
    public DateTime Datetime { get; set; }
    public int Month { get; set; }
    public int? Projectid { get; set; }
    public byte Secondarytype { get; set; }
}

public sealed class SqlTblAutoprocesslog : SqlServerEntity
{
    public long Logid { get; set; }
    public string? Processname { get; set; }
    public string? Processkey { get; set; }
    public short? Processversion { get; set; }
    public string? Triggerconfig { get; set; }
    public DateTime? Endtime { get; set; }
    public DateTime? Starttime { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblBankaccount : SqlServerEntity<int>
{
    public string Name { get; set; } = null!;
    public string Number { get; set; } = null!;
    public string? Iban { get; set; }
    public string? Bankbranchname { get; set; }
    public string? Ownername { get; set; }
    public int Shopid { get; set; }
    public string? Cardnumber { get; set; }
    public bool Isenabled { get; set; }
    public bool Isdefault { get; set; }
    public string? Description { get; set; }
    public string Currency { get; set; } = null!;
    public string Bank { get; set; } = null!;
    public long Detailaccountid { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblCashfund : SqlServerEntity<int>
{
    public string Name { get; set; } = null!;
    public string? Description { get; set; }
    public bool Isenabled { get; set; }
    public int Shopid { get; set; }
    public bool Isdefault { get; set; }
    public string Currency { get; set; } = null!;
    public long Detailaccountid { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblCheck : SqlServerEntity
{
    public int Checkid { get; set; }
    public string Serialnumber { get; set; } = null!;
    public DateOnly Duedate { get; set; }
    public decimal Amount { get; set; }
    public byte Status { get; set; }
    public DateTime Statusdatetime { get; set; }
    public string? Sayadnumber { get; set; }
    public string? Description { get; set; }
    public string? Payee { get; set; }
    public string? Payeenationalid { get; set; }
    public int Shopid { get; set; }
    public int? Bankaccountid { get; set; }
    public DateTime Issuedate { get; set; }
    public string? Bankbranch { get; set; }
    public string? Bank { get; set; }
    public int Personid { get; set; }
    public bool Isreceipt { get; set; }
    public string Currency { get; set; } = null!;
    public decimal Exchangerate { get; set; }
    public int? Projectid { get; set; }
    public int Fiscalperiodid { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblCredittransaction : SqlServerEntity<int>
{
    public string Userid { get; set; } = null!;
    public decimal Amount { get; set; }
    public byte Type { get; set; }
    public int Referenceid { get; set; }
    public string? Description { get; set; }
    public DateTime Datetime { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblDetailaccount : SqlServerEntity
{
    public long Detailaccountid { get; set; }
    public int Shopid { get; set; }
    public string Entitytype { get; set; } = null!;
    public string Name { get; set; } = null!;
    public int? Referenceid { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblEntityfile : SqlServerEntity<int>
{
    public int? Shopid { get; set; }
    public byte Entitytype { get; set; }
    public int Entityid { get; set; }
    public string Originalname { get; set; } = null!;
    public string Uniquename { get; set; } = null!;
    public long Size { get; set; }
    public string Relativeurl { get; set; } = null!;
    public string Type { get; set; } = null!;
    public DateTime Createdat { get; set; }
    public string? Description { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblEntitynote : SqlServerEntity<long>
{
    public int Shopid { get; set; }
    public long Entityid { get; set; }
    public byte Entitytype { get; set; }
    public string Note { get; set; } = null!;
    public bool Ispublic { get; set; }
    public string Createdby { get; set; } = null!;
    public DateTime Createdtime { get; set; }
    public DateTime? Updatedtime { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblGeneralconfig : SqlServerEntity
{
    public int Configid { get; set; }
    public int Shopid { get; set; }
    public string Basecurrency { get; set; } = null!;
    public string Timezone { get; set; } = null!;
    public string Calendartype { get; set; } = null!;
    public decimal? Defaultvatrate { get; set; }
    public bool Ismulticurrencyenabled { get; set; }
    public string? Othercurrencies { get; set; }
    public bool Alloweditopeningbalance { get; set; }
    public bool Autoapprovesystemgenerateddocuments { get; set; }
    public bool Iswarehouseenabled { get; set; }
    public string? TenantId { get; set; }
    public bool? Allownegativephysicalstock { get; set; }
    public string? Trackingmethod { get; set; }
    public string? Valuationmethod { get; set; }
    public DateOnly? Storageexpirationdate { get; set; }
    public int Storagesize { get; set; }
}

public sealed class SqlTblGlobalconfig : SqlServerEntity
{
    public string Key { get; set; } = null!;
    public string Value { get; set; } = null!;
    public string? TenantId { get; set; }
}

public sealed class SqlTblGlobalproduct : SqlServerEntity
{
    public int Globalproductid { get; set; }
    public string Name { get; set; } = null!;
    public string? Barcode { get; set; }
    public string? Description { get; set; }
    public bool Ispublished { get; set; }
    public short? Brandid { get; set; }
    public short Unitcode { get; set; }
    public bool Isenabled { get; set; }
    public bool Isapproved { get; set; }
    public byte Reviewstatusid { get; set; }
    public DateTime Createtime { get; set; }
    public string? Creatoruser { get; set; }
    public DateTime Updatetime { get; set; }
    public string? Updateruser { get; set; }
    public decimal Saletaxrate { get; set; }
    public decimal Purchasetaxrate { get; set; }
    public bool Isservice { get; set; }
    public short? Groupid { get; set; }
    public string? Imagerelativeurl { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblGlobalproductgroup : SqlServerEntity
{
    public short Groupid { get; set; }
    public short? Parentid { get; set; }
    public string Name { get; set; } = null!;
    public string? TenantId { get; set; }
}

public sealed class SqlTblGlobalproductmedia : SqlServerEntity
{
    public int Mediaid { get; set; }
    public int Productid { get; set; }
    public string? Filerelativeurl { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblGroups : SqlServerEntity
{
    public int Shopid { get; set; }
    public int Groupid { get; set; }
    public byte Entitytype { get; set; }
    public int? Parentid { get; set; }
    public int Code { get; set; }
    public string Name { get; set; } = null!;
    public string? Description { get; set; }
    public string? Fullpath { get; set; }
    public string? Namefullpath { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblInventoryfifoconsumption : SqlServerEntity<int>
{
    public int Stockcarditemid { get; set; }
    public int Shopid { get; set; }
    public decimal Consumedquantity { get; set; }
    public decimal Unitcost { get; set; }
    public DateTime Consumptiondatetime { get; set; }
    public decimal? Amount { get; set; }
    public int Productid { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblInventoryfifolayer : SqlServerEntity<int>
{
    public int Stockcarditemid { get; set; }
    public int Productid { get; set; }
    public int Warehouseid { get; set; }
    public int Shopid { get; set; }
    public decimal Initialquantity { get; set; }
    public decimal Remainingquantity { get; set; }
    public decimal Unitcost { get; set; }
    public DateTime Receiptdatetime { get; set; }
    public decimal? Amount { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblIrancities : SqlServerEntity
{
    public short Cityid { get; set; }
    public byte Stateid { get; set; }
    public string Cityname { get; set; } = null!;
    public string? TenantId { get; set; }
}

public sealed class SqlTblIranstates : SqlServerEntity
{
    public byte Stateid { get; set; }
    public string Statename { get; set; } = null!;
    public string? TenantId { get; set; }
}

public sealed class SqlTblMessagehistory : SqlServerEntity
{
    public int Messageid { get; set; }
    public string? Mobilenumber { get; set; }
    public DateTime? Sendtime { get; set; }
    public string? Messagetext { get; set; }
    public string? Errorcode { get; set; }
    public string? Subject { get; set; }
    public string? Errormessage { get; set; }
    public string? TenantId { get; set; }
    public string? Deliverystatus { get; set; }
}

public sealed class SqlTblNotificationconfig : SqlServerEntity
{
    public int Configid { get; set; }
    public int Shopid { get; set; }
    public string Notificationmethod { get; set; } = null!;
    public bool Notifysaleinvoiceduedate { get; set; }
    public byte? Saleinvoiceduenotificationthreshold { get; set; }
    public bool Notifypurchaseinvoiceduedate { get; set; }
    public byte? Purchaseinvoiceduenotificationthreshold { get; set; }
    public bool Notifyreceivedchequeduedate { get; set; }
    public byte? Receivedchequeduenotificationthreshold { get; set; }
    public bool Notifypaidchequeduedate { get; set; }
    public byte? Paidchequeduenotificationthreshold { get; set; }
    public bool Notifyinstallmentduedate { get; set; }
    public byte? Installmentduenotificationthreshold { get; set; }
    public bool Notifyreorderpoint { get; set; }
    public bool Notifytaxinvoicesubmissionduedate { get; set; }
    public byte? Taxinvoicesubmissionduenotificationthreshold { get; set; }
    public bool Notifydocumentlimitreached { get; set; }
    public byte? Documentlimitnotificationthreshold { get; set; }
    public bool Notifyonlineinvoicelimitreached { get; set; }
    public byte? Onlineinvoicenotificationthreshold { get; set; }
    public bool Notifytaxsubmissionlimitreached { get; set; }
    public byte? Taxsubmissionnotificationthreshold { get; set; }
    public bool Notifystoragelimitreached { get; set; }
    public int? Storagenotificationthreshold { get; set; }
    public bool Notifywalletlowbalance { get; set; }
    public decimal? Walletlowbalancethreshold { get; set; }
    public bool Senddailysalesreport { get; set; }
    public string? TenantId { get; set; }
}

[DisplayName("شخص")]
public sealed class SqlTblPerson : SqlServerEntity<int>
{
    public int Shopid { get; set; }
    public long Detailaccountid { get; set; }
    public string? Name { get; set; }
    public string? Lastname { get; set; }
    public string? Companyname { get; set; }
    public string Nickname { get; set; } = null!;
    public byte Type { get; set; }
    public bool Isenabled { get; set; }
    public string? Identifiernumber { get; set; }
    public string? Economiccode { get; set; }
    public string? Branchcode { get; set; }
    public decimal? Creditlimit { get; set; }
    public string? Profileimageurl { get; set; }
    public string? Contactinfo { get; set; }
    public string? Specialdates { get; set; }
    public string? Bankaccountsinfo { get; set; }
    public string? Addressesinfo { get; set; }
    public string? Roles { get; set; }
    public string? Mobilenumber { get; set; }
    public string? Passportnumber { get; set; }
    public string? Contractnumber { get; set; }
    public string? Subscriptionnumber { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblPettycash : SqlServerEntity
{
    public int Pettycashid { get; set; }
    public int Shopid { get; set; }
    public long? Detailaccountid { get; set; }
    public int Personid { get; set; }
    public bool Isdefault { get; set; }
    public bool Isenabled { get; set; }
    public string? Description { get; set; }
    public int Code { get; set; }
    public string Name { get; set; } = null!;
    public string? TenantId { get; set; }
    public string Currency { get; set; } = null!;
}

public sealed class SqlTblPosdevice : SqlServerEntity<int>
{
    public int Shopid { get; set; }
    public bool Isenabled { get; set; }
    public int Bankaccountid { get; set; }
    public string? Description { get; set; }
    public string Name { get; set; } = null!;
    public string Ipaddress { get; set; } = null!;
    public int? Portnumber { get; set; }
    public string? Terminalnumber { get; set; }
    public string? Merchantnumber { get; set; }
    public string? Serialnumber { get; set; }
    public bool Isdefault { get; set; }
    public string Psp { get; set; } = null!;
    public long Detailaccountid { get; set; }
    public string Currency { get; set; } = null!;
    public string? TenantId { get; set; }
}

public sealed class SqlTblPrintconfig : SqlServerEntity
{
    public int Configid { get; set; }
    public int Shopid { get; set; }
    public bool Printlogo { get; set; }
    public string Invoicetitle { get; set; } = null!;
    public bool Printsellerinfo { get; set; }
    public bool Printcustomerinfo { get; set; }
    public bool Printsignaturearea { get; set; }
    public string? Signaturetitle1 { get; set; }
    public string? Signaturetitle2 { get; set; }
    public string? Signaturetitle3 { get; set; }
    public string? Signaturetitle4 { get; set; }
    public string? Signaturetitle5 { get; set; }
    public bool Printduedate { get; set; }
    public string Taxprintmethod { get; set; } = null!;
    public string Discountprintmethod { get; set; } = null!;
    public bool Printpaymentinfo { get; set; }
    public bool Printaccountbalance { get; set; }
    public bool Printcurrentdatetime { get; set; }
    public string? Invoicefootertext { get; set; }
    public byte Printcopycount { get; set; }
    public bool Printinvoiceitemcount { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblProduct : SqlServerEntity<int>
{
    public int Shopid { get; set; }
    public int? Globalid { get; set; }
    public string? Taxcode { get; set; }
    public string Name { get; set; } = null!;
    public bool Isenabled { get; set; }
    public short Baseunit { get; set; }
    public short? Secondaryunit { get; set; }
    public decimal? Unitconversionfactor { get; set; }
    public decimal Purchaseprice { get; set; }
    public decimal Purchasetaxrate { get; set; }
    public decimal Saleprice { get; set; }
    public decimal Saletaxrate { get; set; }
    public decimal Percentdiscount { get; set; }
    public decimal Fixeddiscount { get; set; }
    public bool? Isconsumable { get; set; }
    public bool Ispurchasable { get; set; }
    public bool Isstockable { get; set; }
    public bool Issellable { get; set; }
    public bool Isonlinesellable { get; set; }
    public bool Isservice { get; set; }
    public bool? Isserialized { get; set; }
    public long Detailaccountid { get; set; }
    public string? Imagerelativeurl { get; set; }
    public decimal? Maxsalesquantity { get; set; }
    public string? Description { get; set; }
    public decimal Accountingstock { get; set; }
    public decimal? Minimumstock { get; set; }
    public int? Groupid { get; set; }
    public decimal? Reorderpoint { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblProductbarcode : SqlServerEntity
{
    public int Barcodeid { get; set; }
    public int Productid { get; set; }
    public string Barcode { get; set; } = null!;
    public int Shopid { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblProductbrand : SqlServerEntity
{
    public short Brandid { get; set; }
    public string Brandname { get; set; } = null!;
    public string? Branddescription { get; set; }
    public string? TenantId { get; set; }
    public string? Logorelativeurl { get; set; }
}

public sealed class SqlTblProductreviewstatus : SqlServerEntity
{
    public byte Productreviewstatusid { get; set; }
    public string Productreviewstatusname { get; set; } = null!;
    public string? TenantId { get; set; }
}

public sealed class SqlTblProductunit : SqlServerEntity
{
    public string Name { get; set; } = null!;
    public byte Decimalprecision { get; set; }
    public string? TenantId { get; set; }
    public short Unitcode { get; set; }
    public string Usagetype { get; set; } = null!;
    public bool Countassingleitem { get; set; }
    public string? Conversions { get; set; }
}

public sealed class SqlTblProject : SqlServerEntity
{
    public int Projectid { get; set; }
    public int Shopid { get; set; }
    public string Name { get; set; } = null!;
    public bool Isdefault { get; set; }
    public bool Isenabled { get; set; }
    public string? Description { get; set; }
    public byte Code { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblPurchaseorder : SqlServerEntity
{
    public long Purchaseorderid { get; set; }
    public decimal Totalamountbeforediscount { get; set; }
    public decimal Totalvatamount { get; set; }
    public decimal Totalinvoiceamount { get; set; }
    public decimal Totaldiscountamount { get; set; }
    public string? TenantId { get; set; }
    public int Shopid { get; set; }
    public string? Shippingdescription { get; set; }
    public decimal? Shippingamount { get; set; }
    public string? Endorsementid { get; set; }
    public string? Insuranceid { get; set; }
    public DateOnly? Salesnoticedate { get; set; }
    public string? Salesnoticenumber { get; set; }
    public string? Shippedproducts { get; set; }
    public string? Driveridentificationnumber { get; set; }
    public string? Fleetnumber { get; set; }
    public byte? Waybilltype { get; set; }
    public string? Receiveridentificationnumber { get; set; }
    public string? Senderidentificationnumber { get; set; }
    public string? Destinationcity { get; set; }
    public string? Destinationcountry { get; set; }
    public string? Origincity { get; set; }
    public string? Origincountry { get; set; }
    public string? Referencewaybillnumber { get; set; }
    public string? Waybillnumber { get; set; }
    public string? Agencyeconomiccode { get; set; }
    public decimal? Totalcurrencyamount { get; set; }
    public decimal? Totalrialamount { get; set; }
    public decimal? Totalnetweight { get; set; }
    public string? Subscribernumber { get; set; }
    public DateOnly? Customsdeclarationdate { get; set; }
    public string? Customsdeclarationnumber { get; set; }
    public byte? Flighttype { get; set; }
    public decimal? Totalarticle17taxamount { get; set; }
    public decimal? Totalvatpaidamount { get; set; }
    public decimal? Totalcreditamount { get; set; }
    public decimal? Totalcashpaidamount { get; set; }
    public byte? Settlementtypeid { get; set; }
    public string? Taxuniqueid { get; set; }
    public decimal Adjustmentsamount { get; set; }
    public decimal? Totalothertaxesandchargesamount { get; set; }
    public string? Sellercustomsofficecode { get; set; }
    public string? Adjustments { get; set; }
    public DateOnly? Duedate { get; set; }
    public string? Customspermitnumber { get; set; }
    public string? Description { get; set; }
    public byte Invoiceformat { get; set; }
    public string? Taxinvoiceinternalserial { get; set; }
    public decimal Totalamount { get; set; }
    public decimal Paidamount { get; set; }
    public byte? Invoicetype { get; set; }
    public decimal Totalamountafterdiscount { get; set; }
    public byte Paymentstatus { get; set; }
    public byte? Inventorystatus { get; set; }
    public byte? Deliverystatus { get; set; }
    public int Supplierid { get; set; }
    public byte Status { get; set; }
    public DateTime Issuedatetime { get; set; }
    public int Invoicenumber { get; set; }
    public decimal Exchangerate { get; set; }
    public string Currency { get; set; } = null!;
    public int? Projectid { get; set; }
    public int? Warehouseid { get; set; }
    public int Fiscalperiodid { get; set; }
    public decimal? Remainedamount { get; set; }
    public bool Isstockcardautocreated { get; set; }
}

public sealed class SqlTblPurchaseorderitem : SqlServerEntity
{
    public long Purchaseorderitemid { get; set; }
    public long Purchaseorderid { get; set; }
    public int Productid { get; set; }
    public decimal? Quantity { get; set; }
    public short? Unit { get; set; }
    public decimal? Price { get; set; }
    public decimal? Linepercentdiscount { get; set; }
    public decimal Linetotalamount { get; set; }
    public string? TenantId { get; set; }
    public decimal Vatrate { get; set; }
    public decimal? Unitconversionfactor { get; set; }
    public decimal? Linevatpaidamount { get; set; }
    public decimal? Linecashpaidamount { get; set; }
    public decimal? Otherlegalduesamount { get; set; }
    public decimal? Otherlegalduesrate { get; set; }
    public string? Otherlegalduessubject { get; set; }
    public decimal? Othertaxesandchargesamount { get; set; }
    public decimal? Othertaxesandchargesrate { get; set; }
    public string? Othertaxesandchargessubject { get; set; }
    public decimal? Vatbaseamount { get; set; }
    public decimal? Vatcalculationbase { get; set; }
    public decimal? Currencybuyrate { get; set; }
    public decimal? Purity { get; set; }
    public decimal? Totalmakingcommissionprofit { get; set; }
    public decimal? Commission { get; set; }
    public decimal? Sellerprofit { get; set; }
    public decimal? Makingcharge { get; set; }
    public decimal? Linecurrencyvalue { get; set; }
    public decimal? Linerialvalue { get; set; }
    public decimal? Netweight { get; set; }
    public decimal Lineamountafterdiscount { get; set; }
    public string? Commissioncontractnumber { get; set; }
    public decimal Linediscountamount { get; set; }
    public decimal Lineamountbeforediscount { get; set; }
    public decimal? Linecurrencyamount { get; set; }
    public decimal Vatamount { get; set; }
    public decimal? Lineexchangerate { get; set; }
    public string? Linecurrency { get; set; }
    public int? Projectid { get; set; }
    public int? Linewarehouseid { get; set; }
    public int Fiscalperiodid { get; set; }
    public int Shopid { get; set; }
}

public sealed class SqlTblPurchaseorderreturn : SqlServerEntity
{
    public long Purchaseorderreturnid { get; set; }
    public int Shopid { get; set; }
    public int Fiscalperiodid { get; set; }
    public int? Warehouseid { get; set; }
    public int? Projectid { get; set; }
    public long Referencepurchaseorderid { get; set; }
    public int Invoicenumber { get; set; }
    public DateTime Issuedatetime { get; set; }
    public DateTime Creationdatetime { get; set; }
    public byte Status { get; set; }
    public byte? Deliverystatus { get; set; }
    public byte? Inventorystatus { get; set; }
    public byte Paymentstatus { get; set; }
    public decimal Totalreturnamountbeforediscount { get; set; }
    public decimal Totaldiscountreturnamount { get; set; }
    public decimal Totalreturnamountafterdiscount { get; set; }
    public decimal Totalvatreturnamount { get; set; }
    public decimal Totalinvoicereturnamount { get; set; }
    public decimal Paidreturnamount { get; set; }
    public decimal Totalreturnamount { get; set; }
    public string? Description { get; set; }
    public string? Adjustments { get; set; }
    public decimal Adjustmentsamount { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblPurchaseorderreturnitem : SqlServerEntity
{
    public long Purchaseorderreturnitemid { get; set; }
    public long Referencepurchaseorderitemid { get; set; }
    public long Purchaseorderreturnid { get; set; }
    public int Shopid { get; set; }
    public int Fiscalperiodid { get; set; }
    public int? Linewarehouseid { get; set; }
    public int? Projectid { get; set; }
    public int Productid { get; set; }
    public decimal Returnquantity { get; set; }
    public short Unit { get; set; }
    public decimal? Unitconversionfactor { get; set; }
    public decimal Price { get; set; }
    public decimal Linereturnamountbeforediscount { get; set; }
    public decimal? Linepercentdiscount { get; set; }
    public decimal Linediscountreturnamount { get; set; }
    public decimal Linereturnamountafterdiscount { get; set; }
    public decimal Vatrate { get; set; }
    public decimal Vatreturnamount { get; set; }
    public decimal Linetotalreturnamount { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblReleasenote : SqlServerEntity
{
    public byte Releaseid { get; set; }
    public DateOnly Releasedate { get; set; }
    public string Releaseversion { get; set; } = null!;
    public string? TenantId { get; set; }
}

public sealed class SqlTblReleasenoteitem : SqlServerEntity
{
    public short Releaseitemid { get; set; }
    public byte Releaseid { get; set; }
    public byte Releaseitemorder { get; set; }
    public string Releaseitemtitle { get; set; } = null!;
    public string? Releaseitemdescription { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblSaleorder : SqlServerEntity
{
    public long Saleorderid { get; set; }
    public decimal Totalamountbeforediscount { get; set; }
    public decimal Totalvatamount { get; set; }
    public decimal Totaldiscountamount { get; set; }
    public decimal Totalinvoiceamount { get; set; }
    public string? TenantId { get; set; }
    public int Shopid { get; set; }
    public string? Shippingdescription { get; set; }
    public decimal? Shippingamount { get; set; }
    public int? Courierid { get; set; }
    public string? Taxpayerportalinquiryresponse { get; set; }
    public string? Endorsementid { get; set; }
    public string? Insuranceid { get; set; }
    public DateOnly? Salesnoticedate { get; set; }
    public string? Salesnoticenumber { get; set; }
    public string? Shippedproducts { get; set; }
    public string? Driveridentificationnumber { get; set; }
    public string? Fleetnumber { get; set; }
    public byte? Waybilltype { get; set; }
    public string? Receiveridentificationnumber { get; set; }
    public string? Senderidentificationnumber { get; set; }
    public string? Destinationcity { get; set; }
    public string? Destinationcountry { get; set; }
    public string? Origincity { get; set; }
    public string? Origincountry { get; set; }
    public string? Referencewaybillnumber { get; set; }
    public string? Waybillnumber { get; set; }
    public string? Agencyeconomiccode { get; set; }
    public decimal? Totalcurrencyamount { get; set; }
    public decimal? Totalrialamount { get; set; }
    public decimal? Totalnetweight { get; set; }
    public string? Subscribernumber { get; set; }
    public DateOnly? Customsdeclarationdate { get; set; }
    public string? Customsdeclarationnumber { get; set; }
    public string? Customerpassportnumber { get; set; }
    public byte? Flighttype { get; set; }
    public decimal Adjustmentsamount { get; set; }
    public string? Adjustments { get; set; }
    public DateOnly? Duedate { get; set; }
    public string? Description { get; set; }
    public byte Taxpayerportalstatus { get; set; }
    public decimal? Totalarticle17taxamount { get; set; }
    public decimal? Totalvatpaidamount { get; set; }
    public decimal? Totalcreditamount { get; set; }
    public decimal? Totalcashpaidamount { get; set; }
    public byte? Settlementtypeid { get; set; }
    public decimal Totalamount { get; set; }
    public decimal Paidamount { get; set; }
    public decimal Totalamountafterdiscount { get; set; }
    public decimal? Totalothertaxesandchargesamount { get; set; }
    public byte Paymentstatus { get; set; }
    public byte? Inventorystatus { get; set; }
    public byte? Deliverystatus { get; set; }
    public byte Status { get; set; }
    public string? Contractnumber { get; set; }
    public string? Sellercustomsofficecode { get; set; }
    public string? Customspermitnumber { get; set; }
    public string? Customerbranchcode { get; set; }
    public string? Customerpostalcode { get; set; }
    public string? Sellerbranchcode { get; set; }
    public string? Customereconomiccode { get; set; }
    public string? Customeridentificationnumber { get; set; }
    public byte? Customerpersontype { get; set; }
    public string? Sellereconomiccode { get; set; }
    public int Customerid { get; set; }
    public int? Salespersonid { get; set; }
    public byte Invoicesubject { get; set; }
    public byte Invoiceformat { get; set; }
    public string? Referencetaxuniqueid { get; set; }
    public string? Taxinvoiceinternalserial { get; set; }
    public byte? Invoicetype { get; set; }
    public DateTime Creationdatetime { get; set; }
    public DateTime Issuedatetime { get; set; }
    public string? Taxuniqueid { get; set; }
    public int Invoicenumber { get; set; }
    public decimal Exchangerate { get; set; }
    public string Currency { get; set; } = null!;
    public int Fiscalperiodid { get; set; }
    public int? Projectid { get; set; }
    public int? Warehouseid { get; set; }
    public long? Referencesaleorderid { get; set; }
    public decimal? Remainedamount { get; set; }
    public bool Isstockcardautocreated { get; set; }
}

public sealed class SqlTblSaleorderconfig : SqlServerEntity
{
    public int Configid { get; set; }
    public bool Updatesalepriceoninvoicesave { get; set; }
    public bool Updatepurchasepriceoninvoicesave { get; set; }
    public bool Notifyuserafterpriceupdate { get; set; }
    public bool Allowlowstocksale { get; set; }
    public bool Showzeronegativestockitems { get; set; }
    public bool Allowduplicateitemsininvoice { get; set; }
    public bool Checkcustomercreditonsale { get; set; }
    public bool Warnsalebelowpurchaseprice { get; set; }
    public bool Showprofitininvoice { get; set; }
    public int? Defaultcustomer { get; set; }
    public bool Salespersonrequired { get; set; }
    public bool Enableautowarehouseissue { get; set; }
    public string Invoiceprintmethod { get; set; } = null!;
    public bool Enablescale { get; set; }
    public int Shopid { get; set; }
    public string? TenantId { get; set; }
    public byte Paymentpageopeningmode { get; set; }
}

public sealed class SqlTblSaleorderitem : SqlServerEntity
{
    public long Saleorderitemid { get; set; }
    public long Saleorderid { get; set; }
    public int Productid { get; set; }
    public decimal? Quantity { get; set; }
    public short? Unit { get; set; }
    public decimal? Price { get; set; }
    public decimal? Linepercentdiscount { get; set; }
    public decimal Linetotalamount { get; set; }
    public string? TenantId { get; set; }
    public decimal? Cost { get; set; }
    public decimal Vatrate { get; set; }
    public decimal? Unitconversionfactor { get; set; }
    public decimal Vatamount { get; set; }
    public string? Productdescription { get; set; }
    public string? Producttaxcode { get; set; }
    public int? Projectid { get; set; }
    public int? Linewarehouseid { get; set; }
    public int Fiscalperiodid { get; set; }
    public int Shopid { get; set; }
    public decimal? Vatbaseamount { get; set; }
    public decimal? Vatcalculationbase { get; set; }
    public decimal? Currencybuyrate { get; set; }
    public decimal? Purity { get; set; }
    public decimal? Totalmakingcommissionprofit { get; set; }
    public decimal? Commission { get; set; }
    public decimal? Sellerprofit { get; set; }
    public decimal? Makingcharge { get; set; }
    public decimal? Linecurrencyvalue { get; set; }
    public string? Commissioncontractnumber { get; set; }
    public decimal? Linerialvalue { get; set; }
    public decimal? Netweight { get; set; }
    public decimal? Linevatpaidamount { get; set; }
    public decimal? Linecashpaidamount { get; set; }
    public decimal? Otherlegalduesamount { get; set; }
    public decimal? Otherlegalduesrate { get; set; }
    public string? Otherlegalduessubject { get; set; }
    public decimal? Othertaxesandchargesamount { get; set; }
    public decimal? Othertaxesandchargesrate { get; set; }
    public string? Othertaxesandchargessubject { get; set; }
    public decimal Lineamountafterdiscount { get; set; }
    public decimal Linediscountamount { get; set; }
    public decimal Lineamountbeforediscount { get; set; }
    public decimal? Linecurrencyamount { get; set; }
    public decimal? Lineexchangerate { get; set; }
    public string? Linecurrency { get; set; }
}

public sealed class SqlTblSaleorderreturn : SqlServerEntity
{
    public long Saleorderreturnid { get; set; }
    public int Shopid { get; set; }
    public int Fiscalperiodid { get; set; }
    public int? Warehouseid { get; set; }
    public int? Projectid { get; set; }
    public long Referencesaleorderid { get; set; }
    public int Invoicenumber { get; set; }
    public DateTime Issuedatetime { get; set; }
    public DateTime Creationdatetime { get; set; }
    public byte Status { get; set; }
    public byte? Deliverystatus { get; set; }
    public byte? Inventorystatus { get; set; }
    public byte Paymentstatus { get; set; }
    public decimal Totalreturnamountbeforediscount { get; set; }
    public decimal Totaldiscountreturnamount { get; set; }
    public decimal Totalreturnamountafterdiscount { get; set; }
    public decimal Totalvatreturnamount { get; set; }
    public decimal? Totalothertaxesandchargesreturnamount { get; set; }
    public decimal Totalinvoicereturnamount { get; set; }
    public decimal Paidreturnamount { get; set; }
    public decimal Totalreturnamount { get; set; }
    public string? Description { get; set; }
    public string? Adjustments { get; set; }
    public decimal Adjustmentsamount { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblSaleorderreturnitem : SqlServerEntity
{
    public long Saleorderreturnitemid { get; set; }
    public long Referencesaleorderitemid { get; set; }
    public long Saleorderreturnid { get; set; }
    public int Shopid { get; set; }
    public int Fiscalperiodid { get; set; }
    public int? Linewarehouseid { get; set; }
    public int? Projectid { get; set; }
    public int Productid { get; set; }
    public decimal Returnquantity { get; set; }
    public short Unit { get; set; }
    public decimal? Unitconversionfactor { get; set; }
    public decimal Price { get; set; }
    public decimal Linereturnamountbeforediscount { get; set; }
    public decimal? Linepercentdiscount { get; set; }
    public decimal Linediscountreturnamount { get; set; }
    public decimal Linereturnamountafterdiscount { get; set; }
    public decimal Vatrate { get; set; }
    public decimal Vatreturnamount { get; set; }
    public decimal Linetotalreturnamount { get; set; }
    public decimal? Othertaxesandchargesreturnamount { get; set; }
    public decimal? Otherlegalduesreturnamount { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblServicediscount : SqlServerEntity<short>
{
    public string Name { get; set; } = null!;
    public string Code { get; set; } = null!;
    public DateOnly? Startdate { get; set; }
    public DateOnly? Enddate { get; set; }
    public bool Ispublic { get; set; }
    public decimal Percentamount { get; set; }
    public decimal Fixedamount { get; set; }
    public string? Description { get; set; }
    public bool Isenabled { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblServicepayment : SqlServerEntity
{
    public int Paymentid { get; set; }
    public string? Invoicenumber { get; set; }
    public string? Invoicedate { get; set; }
    public string? Transactionreferenceid { get; set; }
    public decimal? Amount { get; set; }
    public DateTime? Transactiondate { get; set; }
    public long? Referencenumber { get; set; }
    public string? Maskedcardnumber { get; set; }
    public long? Shaparakrefnumber { get; set; }
    public bool? Issuccess { get; set; }
    public string? Message { get; set; }
    public long? Tracenumber { get; set; }
    public DateTime? Registertime { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblServiceplan : SqlServerEntity
{
    public byte Planid { get; set; }
    public string Planname { get; set; } = null!;
    public string? Plandescription { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblServicerequest : SqlServerEntity<int>
{
    public int? Shopid { get; set; }
    public byte? Subscriptionid { get; set; }
    public byte Status { get; set; }
    public DateTime Requesttime { get; set; }
    public int? Paymentid { get; set; }
    public decimal Price { get; set; }
    public short? Discountid { get; set; }
    public decimal Discountamount { get; set; }
    public decimal Payableamount { get; set; }
    public DateOnly? Subscriptionstartdate { get; set; }
    public DateOnly? Subscriptionenddate { get; set; }
    public string? TenantId { get; set; }
    public string Userid { get; set; } = null!;
    public decimal Taxamount { get; set; }
}

public sealed class SqlTblServicesubscription : SqlServerEntity
{
    public byte Subscriptionid { get; set; }
    public string Subscriptionname { get; set; } = null!;
    public byte Planid { get; set; }
    public decimal Subscriptionprice { get; set; }
    public string? Subscriptiondescription { get; set; }
    public bool Subscriptionenable { get; set; }
    public bool Subscriptiondefault { get; set; }
    public string? TenantId { get; set; }
    public decimal Percentdiscount { get; set; }
    public decimal Fixeddiscount { get; set; }
    public decimal Subscriptiontaxrate { get; set; }
    public short Subscriptiondays { get; set; }
    public decimal? Subscriptionpayableamount { get; set; }
    public decimal? Subscriptiontaxamount { get; set; }
}

[DisplayName("سهامدار")]
public sealed class SqlTblShareholder : SqlServerEntity
{
    public int Shareholderid { get; set; }
    public int Shopid { get; set; }
    public int Fiscalperiodid { get; set; }
    public int Personid { get; set; }
    public decimal Sharepercent { get; set; }
    public string? Description { get; set; }
    public decimal? Initialcapitalshare { get; set; }
    public string? TenantId { get; set; }
}

[DisplayName("مغازه")]
public sealed class SqlTblShop : SqlServerEntity
{
    public int Shopid { get; set; }
    public string Ownerid { get; set; } = null!;
    public string Name { get; set; } = null!;
    public string? Description { get; set; }
    public string? Addressline { get; set; }
    public string? Postalcode { get; set; }
    public string? Email { get; set; }
    public string? Phone { get; set; }
    public string? Economiccode { get; set; }
    public string? Identifiernumber { get; set; }
    public string? TenantId { get; set; }
    public byte? Activitytypeid { get; set; }
    public string? Logorelativeurl { get; set; }
    public string? Mobile { get; set; }
    public string? Branchcode { get; set; }
    public string? Country { get; set; }
    public string? Website { get; set; }
    public byte Type { get; set; }
    public string? Province { get; set; }
    public string? City { get; set; }
    public byte Status { get; set; }
}

public sealed class SqlTblShopactivitytype : SqlServerEntity
{
    public byte Activitytypeid { get; set; }
    public string Activitytypename { get; set; } = null!;
    public string? TenantId { get; set; }
}

public sealed class SqlTblShopfiscalperiod : SqlServerEntity
{
    public int Fiscalperiodid { get; set; }
    public string Fiscalperiodname { get; set; } = null!;
    public string? Fiscalperioddescription { get; set; }
    public DateOnly Startdate { get; set; }
    public DateOnly Enddate { get; set; }
    public int Shopid { get; set; }
    public byte Fiscalperiodstatusid { get; set; }
    public bool Firstperiod { get; set; }
    public int Lastdocumentnumber { get; set; }
    public int Lastreferencenumber { get; set; }
    public DateTime? Lastdocumentdatetime { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblShopnotification : SqlServerEntity
{
    public int Notificationid { get; set; }
    public byte Notificationtypeid { get; set; }
    public string? Notificationtitle { get; set; }
    public string Notificationtext { get; set; } = null!;
    public bool Notificationcloseallowed { get; set; }
    public DateTime Notificationstarttime { get; set; }
    public DateTime Notificationendtime { get; set; }
    public bool Notificationallshops { get; set; }
    public bool Notificationallmemberroles { get; set; }
    public string? TenantId { get; set; }
    public bool Isbanner { get; set; }
}

public sealed class SqlTblShopnotificationinmemberrole : SqlServerEntity
{
    public int Notificationinmemberroleid { get; set; }
    public int Notificationid { get; set; }
    public byte Memberroleid { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblShopnotificationinshop : SqlServerEntity
{
    public int Notificationinshopid { get; set; }
    public int Notificationid { get; set; }
    public int Shopid { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblShopnotificationtype : SqlServerEntity
{
    public byte Notificationtypeid { get; set; }
    public string Notificationtypename { get; set; } = null!;
    public string? TenantId { get; set; }
}

public sealed class SqlTblStockcard : SqlServerEntity<int>
{
    public int Warehouseid { get; set; }
    public int Shopid { get; set; }
    public int Fiscalperiodid { get; set; }
    public int? Projectid { get; set; }
    public DateTime Datetime { get; set; }
    public int Number { get; set; }
    public string? Description { get; set; }
    public int? Personid { get; set; }
    public bool Direction { get; set; }
    public byte Referencetype { get; set; }
    public long? Referenceid { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblStockcarditem : SqlServerEntity<int>
{
    public int Stockcardid { get; set; }
    public int Shopid { get; set; }
    public int Productid { get; set; }
    public decimal Quantity { get; set; }
    public bool Showinsecondunit { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblStocktaking : SqlServerEntity<int>
{
    public int Shopid { get; set; }
    public int Warehouseid { get; set; }
    public int Fiscalperiodid { get; set; }
    public int? Projectid { get; set; }
    public string? Description { get; set; }
    public byte Status { get; set; }
    public DateTime Datetime { get; set; }
    public int? Number { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblStocktakingitem : SqlServerEntity<int>
{
    public int Stocktakingid { get; set; }
    public int Shopid { get; set; }
    public int Productid { get; set; }
    public decimal Initialquantity { get; set; }
    public decimal? Finalquantity { get; set; }
    public bool Showinsecondunit { get; set; }
    public decimal? Unitcost { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblTag : SqlServerEntity<int>
{
    public int Shopid { get; set; }
    public string Value { get; set; } = null!;
    public byte Entitytype { get; set; }
    public string? Description { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblTaxpayerportalconfig : SqlServerEntity
{
    public int Configid { get; set; }
    public int Shopid { get; set; }
    public bool Istaxpayerportalenabled { get; set; }
    public string? Taxmemoryuniqueid { get; set; }
    public string? Privatekey { get; set; }
    public string? Digitalsignaturecertificate { get; set; }
    public byte Invoiceformat { get; set; }
    public byte? Invoicetype { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblTransfer : SqlServerEntity
{
    public int Transferid { get; set; }
    public int Shopid { get; set; }
    public int Fiscalperiodid { get; set; }
    public int? Projectid { get; set; }
    public string? Description { get; set; }
    public decimal Totalamount { get; set; }
    public DateTime Datetime { get; set; }
    public string Currency { get; set; } = null!;
    public decimal Exchangerate { get; set; }
    public byte Transfertype { get; set; }
    public byte? Referencetype { get; set; }
    public long? Referenceid { get; set; }
    public int Number { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblTransferitem : SqlServerEntity
{
    public int Transferitemid { get; set; }
    public int Transferid { get; set; }
    public int Shopid { get; set; }
    public byte Transfertype { get; set; }
    public bool Isdestination { get; set; }
    public decimal Amount { get; set; }
    public decimal Commission { get; set; }
    public string? Description { get; set; }
    public int Accountid { get; set; }
    public int? Entityid { get; set; }
    public int? Checkid { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblUploadfile : SqlServerEntity<int>
{
    public string Originalname { get; set; } = null!;
    public string Name { get; set; } = null!;
    public string Extension { get; set; } = null!;
    public long Size { get; set; }
    public string Uid { get; set; } = null!;
    public string Relativeurl { get; set; } = null!;
    public string Filetype { get; set; } = null!;
    public DateTime Createtime { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblUseractionlog : SqlServerEntity<long>
{
    public int Shopid { get; set; }
    public string Userid { get; set; } = null!;
    public byte Actiontype { get; set; }
    public byte? Entitytype { get; set; }
    public long? Entityid { get; set; }
    public string? Details { get; set; }
    public DateTime Datetime { get; set; }
    public long? Parentid { get; set; }
    public string? TenantId { get; set; }
}

public sealed class SqlTblWarehouse : SqlServerEntity<int>
{
    public string Name { get; set; } = null!;
    public int Shopid { get; set; }
    public bool Isdefault { get; set; }
    public string? TenantId { get; set; }
    public bool Isenabled { get; set; }
    public long Detailaccountid { get; set; }
    public string? Description { get; set; }
    public int Personid { get; set; }
    public string? Phone { get; set; }
    public string? Address { get; set; }
}

public sealed class SqlViewAccountbalance : SqlServerEntity
{
    public DateOnly Documentdate { get; set; }
    public int Accountid { get; set; }
    public byte Documenttypeid { get; set; }
    public decimal? Totaldebit { get; set; }
    public decimal? Totalcredit { get; set; }
    public long? Cnt { get; set; }
}

public sealed class SqlViewDetailaccountbalance : SqlServerEntity
{
    public int Accountid { get; set; }
    public long? Detailaccountid { get; set; }
    public decimal? Totaldebit { get; set; }
    public decimal? Totalcredit { get; set; }
    public long? Cnt { get; set; }
}

public sealed class SqlVwIntegrationdashboard : SqlServerEntity
{
    public int Shopid { get; set; }
    public string Tenantid { get; set; } = null!;
    public byte Provider { get; set; }
    public string Displayname { get; set; } = null!;
    public bool Isenabled { get; set; }
    public DateTime? Lastsyncatutc { get; set; }
    public int? Mappingcount { get; set; }
    public DateTime? Lastrunatutc { get; set; }
    public int? Failedruns { get; set; }
}
