global using FluentValidation;
global using Hyper.Domain.Entities.Common;
global using MediatR;
global using Microsoft.Extensions.Logging;
global using Neo.Application.Models;
global using Neo.Domain.Features.Client;
global using Neo.Domain.Features.Multilingual;
global using Neo.Domain.Features.Sms;
global using Neo.Domain.Repository;
