<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.GuardClauses" />
    <PackageReference Include="AutoMapper" />
	<PackageReference Include="MassTransit" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
	<PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
	  
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\Neo\src\Neo.Application\Neo.Application.csproj" />
    <ProjectReference Include="..\Hyper.Domain\Hyper.Domain.csproj" />
    <ProjectReference Include="..\Hyper.Infrastructure\Hyper.Infrastructure.csproj" />
  </ItemGroup>

</Project>

